composer.json, composer.lock, config/bolt/config.yaml, config/packages/doctrine.yaml, src/Configuration/Config.php, src/Kernel.php, symfony.lock
- Update Symfony 4.2.x-dev, based on https://github.com/symfony/demo/pull/865
- Added to `composer.json`:
```diff
+"symfony/security-bundle": "4.2.x-dev",
+"symfony/serializer": "4.2.x-dev",
```
- If you _use_ the variables like `bolt.secret` it will be compiled! Inject `\Psr\Container\ContainerInterface $container` in a Controller and then dump it, like so:
- For now, I injected the values from `config.yaml` in `'bolt.config.general'`. I'm not sure how to officially use/inject these in other parts of the application. See https://symfony.com/doc/current/service_container/synthetic_services.html
- It might mean that services use these cannot be auto-wired.
=> Improvements to Bolt Parameters

webpack.config.js
@bobdenotter I just commented out the code that generates the Service Workers files and directories. If you want to get totally rid of Service Workers I can also remove files and packages used for this purpose.
=> Don't generate service workers scripts

assets/js/Views/user.js, templates/_base/layout_blank.html.twig, templates/security/login.html.twig
This PR uses the Password and Text Vue Components for the Login Form.
@JarJak @bobdenotter Maybe Vue Component fields should become more general?. 
The names they are using in the `.twig` files are forcing us to add components called like `editor-label`, `editor-text`, `editor-*` while they are not being part of the editcontent form anymore. In this case is a login form
=> Use Vue Components for Login Form

composer.json, composer.lock
Bump security-checker version as recommended here https://twitter.com/fabpot/status/1067085006542118913
Here #157 we changed the domain but the package version remained at v4.1.
=> Bump security-checker version to ^5.0

.env.dist, .gitignore, .travis.yml, Makefile, README.md, assets/scss/modules/api/api.scss, assets/scss/modules/modules.scss, behat.yml, composer.json, config/packages/api_platform.yaml, config/routes.yaml, easy-coding-standard.yml, public/theme/skeleton/index.twig, public/theme/skeleton/partials/_sub_fields.twig, src/Content/MenuBuilder.php, src/Controller/Frontend/DetailController.php, src/Entity/Content.php, src/Entity/ContentMagicTrait.php, src/Entity/Field.php, src/Entity/Taxonomy.php, src/Entity/User.php, src/Twig/TwigRecordsView.php, symfony.lock, templates/_partials/_flash_messages.html.twig, templates/content/edit.html.twig, tests/api/bootstrap/FeatureContext.php, tests/api/content/get_content.feature
First part of #38.
Custom git repository added to composer.json because I wait for https://github.com/coduo/php-matcher/pull/143
=> Content API Endpoint and Behat tests

Makefile, src/Controller/Backend/ContentEditController.php, src/Controller/Frontend/DetailController.php, src/DataFixtures/ContentFixtures.php, src/Repository/FieldRepository.php, src/Storage/Query/Handler/SelectQueryHandler.php, src/Storage/Query/Query.php, src/Storage/Query/QueryParameterParser.php, src/Storage/Query/QueryResultset.php, src/Twig/Node/SetcontentNode.php, tests/e2e/features/edit_record.feature, tests/e2e/pages/edit_record.js
Inspired by PR by Xiao #286.
Fixes #282 and #283.
This PR can wait for porting setcontent tests from Bolt 3.x #289
=> Yet another setcontent fix

assets/js/app/sidebar/Components/Menu/_SubMenu.vue, src/Content/MenuBuilder.php
Commit cfeff6def1af961e6e826fb5205bb489c6578065 introduced a new small bug: Sidebar items like `Configuration > Users&Permissions` need an `editLink` instead of a `link`.
=> [hotfix] Fix links in sidebar

assets/scss/modules/editor/_tabbar.scss, templates/content/_tabs.html.twig
When you click the tab items in the editor, everything will be set to active state.
The correct ordering is:
```
[role=tablist] > li.nav-item > a.nav-link
```
See: https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior
=> Fix tabbar

assets/js/app/editor/Components/Editor/Embed/Embed.vue, assets/js/app/editor/Components/Editor/index.js, assets/js/app/editor/index.js, composer.json, src/Controller/Async/Embed.php, templates/_partials/fields/embed.html.twig, tests/e2e/features/edit_record.feature, tests/e2e/pages/edit_record.js
Fixes #124 till a certain degree.
I made a simple endpoint for getting the oembed information.
Not sure if we want everything that's from Bolt 3 too?
(This may need improvements with regards to UX. Though that may be a thing for a separate issue)
Implemented CSRF check, but maybe needs to be set in a re-usable `before` interceptor/trait? 🤔
=> Implementation "Embed" Field

src/Entity/Translation.php
=> [Hotfix] Limit length of indexed column to 191, for MySQL 5.6 compatibility

src/DataFixtures/BaseFixture.php, src/DataFixtures/ContentFixtures.php, src/DataFixtures/TaxonomyFixtures.php
This could cause tests to fail, randomly.. We test for "2 categories", but if the fixtures chose "Books" twice, it only stores one. This PR fixes that.
=> Ensure that we get unique random taxonomies for fixtures

easy-coding-standard.yml
Every time we ran ECS, it'd say:
```
$ vendor/bin/ecs check src --fix
PHP Deprecated:  Parameter "exclude_checkers" is deprecated. Use "skip > CheckerClass: ~"
instead. in /Users/bob/Sites/four/vendor/symplify/easy-coding-standard/src/ DependencyInjection/CompilerPass/RemoveExcludedCheckersCompilerPass.php on line 36
Deprecated: Parameter "exclude_checkers" is deprecated. Use "skip > CheckerClass: ~" instead. 
in /Users/bob/Sites/four/vendor/symplify/easy-coding-standard/src/DependencyInjection/ 
CompilerPass/RemoveExcludedCheckersCompilerPass.php on line 36
EasyCodingStandard v5.4.16
```
This PR fixes that.
=> Fix ECS deprecation notices

assets/js/app/toolbar/Components/Toolbar.vue, config/packages/security.yaml, config/routes.yaml, config/services.yaml, templates/_base/layout.html.twig
The backend url can be set in one location now, and i'm passing it into Vue. 
Fixes #245
=> Add 'bolt.backend_url' parameter, so we can change it in one place.

assets/scss/layout/_admin.scss
Done like this to match [this line](https://github.com/bolt/four/blob/bfa8db9fc9f0b87dee3ccbc6ea8baeabffb6f72b/assets/scss/layout/_admin.scss#L83). Although IMHO this can get messy very sooner than later.
=> Fixes #384

assets/js/app/sidebar/Components/Menu/index.vue
This was a tricky one. I don't know if camelCase is how it's supposed to be, but it was causing a false positive while checking `item.contentType !== null`.
=> Fixes #383

composer.json, src/Content/MediaFactory.php, src/Entity/Content.php, src/Entity/ContentExtrasTrait.php, src/Repository/ContentRepository.php, src/Repository/FieldRepository.php, src/Twig/JsonExtension.php, templates/_partials/_content_listing.html.twig
Another approach.
See https://github.com/api-platform/core/pull/2732#discussion_r275135410
Closes #399.
=> Fix integration with API Platform 2.4, the other way around

config/packages/twig.yaml, src/Controller/TwigAwareController.php, templates/_base/layout.html.twig, tests/e2e/features/backend_api.feature, tests/e2e/features/backend_translations.feature, tests/e2e/features/frontend_menu.feature, tests/e2e/pages/backend_api.js, tests/e2e/pages/backend_translations.js
Fixes a regression in #404, where the API and translations screens don't show, because they don't use our controllers, and don't have our `config` set.
=> [hotfix] Make sure `{{ config }}` is set

assets/js/app/listing/Components/Table/Row/_Meta.vue, src/Entity/Content.php, src/Entity/ContentExtrasTrait.php, src/Twig/ContentExtension.php, src/Twig/JsonExtension.php
=> [hotfix] Add missing attributes to json_records

src/Widget/BaseWidget.php, src/Widget/CacheAware.php, src/Widget/CacheTrait.php, src/Widget/NewsWidget.php, src/Widget/SnippetWidget.php, src/Widgets.php, tests/php/Widget/WidgetsTest.php
Makes a big difference, especially for widgets like 'news'...
Before: 
After:
=> Allow for caching of widgets

Makefile, public/theme/skeleton/partials/_recordfooter.twig, src/DataFixtures/BaseFixture.php, src/DataFixtures/ContentFixtures.php, src/DataFixtures/ImageFetchFixtures.php, src/DataFixtures/ImagesFixtures.php, src/DataFixtures/RelationsFixtures.php, src/DataFixtures/TaxonomyFixtures.php, src/DataFixtures/UserFixtures.php, src/Entity/Content.php, src/Repository/RelationRepository.php, src/Twig/ContentExtension.php, src/Twig/RelatedExtension.php, tests/php/Repository/TaxonomyRepositoryTest.php, tests/spec/Bolt/Twig/ContentExtensionSpec.php, tests/spec/Bolt/Twig/RelatedExtensionSpec.php
- Adding Relations as fixtures
- Adding `with-images` and `without-images` groups, to speed up fixtures, if more images are not needed
- Removing 'risky' tests, using them with `--group=without-images` instead. 
Also fixes #252, because tests broke now that Fixtures have relations
=> Expanding on fixtures

src/Widget/Injector/HtmlInjector.php, tests/fixtures/HtmlInjector/index.html, tests/fixtures/HtmlInjector/result.AFTER_BODY_CSS.html, tests/fixtures/HtmlInjector/result.AFTER_BODY_JS.html, tests/fixtures/HtmlInjector/result.AFTER_CSS.html, tests/fixtures/HtmlInjector/result.AFTER_HEAD_CSS.html, tests/fixtures/HtmlInjector/result.AFTER_HEAD_JS.html, tests/fixtures/HtmlInjector/result.AFTER_HEAD_META.html, tests/fixtures/HtmlInjector/result.AFTER_HTML.html, tests/fixtures/HtmlInjector/result.AFTER_JS.html, tests/fixtures/HtmlInjector/result.AFTER_META.html, tests/fixtures/HtmlInjector/result.BEFORE_BODY_CSS.html, tests/fixtures/HtmlInjector/result.BEFORE_BODY_JS.html, tests/fixtures/HtmlInjector/result.BEFORE_CSS.html, tests/fixtures/HtmlInjector/result.BEFORE_HEAD_CSS.html, tests/fixtures/HtmlInjector/result.BEFORE_HEAD_JS.html, tests/fixtures/HtmlInjector/result.BEFORE_HEAD_META.html, tests/fixtures/HtmlInjector/result.BEFORE_HTML.html, tests/fixtures/HtmlInjector/result.BEFORE_JS.html, tests/fixtures/HtmlInjector/result.END_OF_BODY.html, tests/fixtures/HtmlInjector/result.END_OF_HEAD.html, tests/fixtures/HtmlInjector/result.END_OF_HTML.html, tests/fixtures/HtmlInjector/result.START_OF_BODY.html, tests/fixtures/HtmlInjector/result.START_OF_HEAD.html, tests/php/Widget/Injector/HtmlInjectorTest.php
Before: 
```html
<html lang="">
<head>
<title>Aliquam aut eos aspernatur ipsum accusamus. | Bolt Four Website</title>
<link rel="stylesheet" href="/theme/skeleton/css/sakura.css">
</head>
<body>
<meta name="generator" content="Bolt"> <-- INCORRECT
<header>
<h2><a href="/">Bolt Four Website</a></h2>
<p>The amazing payoff goes here</p>
<hr>
</header>
```
After: 
```html
<html lang="">
<head>
<title>Aliquam aut eos aspernatur ipsum accusamus. | Bolt Four Website</title>
<link rel="stylesheet" href="/theme/skeleton/css/sakura.css">
<meta name="generator" content="Bolt"> <-- CORRECT
</head> . 
<body>
<header>
<h2><a href="/">Bolt Four Website</a></h2>
<p>The amazing payoff goes here</p>
<hr>
</header>
```
=> Fix bug in injector where it confused tags like `head` and `header`

src/Widget/CacheTrait.php, src/Widget/Injector/QueueProcessor.php, src/Widget/NewsWidget.php, src/Widget/RequestTrait.php, src/Widget/ResponseTrait.php, src/Widget/StopwatchAware.php, src/Widget/StopwatchTrait.php, src/Widget/TwigTrait.php, src/Widget/WeatherWidget.php, src/Widgets.php, tests/php/Widget/WidgetsTest.php
This PR makes it clear how big the impact of caching widgets can be, if the widgets rely on external sources: 
Not cached:
Cached:
=> Stopwatch trait for widgets

composer.json, symfony.lock
It was already included in the dev-requirements, but it broke when building a project. This PR fixes that. 
See also: https://github.com/symfony/symfony/issues/31720
=> Explicitly require `psr/simple-cache`

composer.json
See: https://github.com/briannesbitt/Carbon/issues/1685
=> Allow for Carbon 2, alongside Carbon 1 (needed for Symfony 4 requirements)

templates/bundles/TranslationBundle/SymfonyProfiler/translation.html.twig, translations/messages.en.xlf, translations/validators.en.xlf
Temporary workaround. Revert when https://github.com/php-translation/symfony-bundle/pull/311 is in a release of PHP-Translation.
=> Workaround for editing translations in backend

assets/scss/layout/_admin.scss, assets/scss/vendor/codemirror.scss, templates/finder/editfile.html.twig
=> Fix too-wide codemirror

src/Extension/ExtensionRegistry.php
As suggested by @drupol here: https://github.com/bolt/core/pull/559#pullrequestreview-270504069
=> Use 'Types::get' to avoid needing try/catch

src/Controller/Backend/ProfileController.php, templates/users/edit.html.twig, translations/messages.en.xlf, translations/messages.hu.xlf, translations/messages.nl.xlf
Found some bug in backend User Edit (or Profile Edit) page in v4.0.0 beta 1.7
- entring invalid or short password leads twig error (missing variable) while notification yields a warning
- notification box contains dummy texts are missing from xlf files
- for admins allowed empty roles selection but template doesn't handles and leads error
ps.: _accidentally I pushed here this branch, I hope didn't make a mess_ :blush:
=> Edit user fixes

src/Repository/UserRepository.php, src/Security/LoginFormAuthenticator.php, tests/php/Repository/UserRepositoryTest.php, tests/php/Security/LoginFormAuthenticatorTest.php, tests/spec/Bolt/Security/LoginFormAuthenticatorSpec.php
Changed the repository method to accept the credential(string) and has
the storage engine compare the lowercase values. At least this is
consistent to the strings compared so it should be a consistent
experience
=> Issue [#514](https://github.com/bolt/core/issues/514)

config/packages/twig.yaml, templates/form/layout.html.twig
This PR fix this errors:
[X] Fix form_themes key in twig config
[X] Update `bootstrap_3_layout.html.twig`
=> fix(config): fix form_themes in twig config

docker/php/Dockerfile
- Update the base container to explicitly use Buster (or the same issue we ran into now is going to crop up whenever Debian has a new release out)
- Use the appropriate ttf-fonts package for Buster
=> Update from Stretch to Buster

composer.json
Very Temporary workaround, until #702 is fixed.
=> Fix `doctrine/dbal` to `2.9.2`, to prevent breakage in tests

src/Controller/Backend/ContentEditController.php
When adding new fields with` localize: true` to new or existing Content entities and then saving the content for the first time the Controller breaks on trying to refresh the Field entity, but the Field Entity is not persisted yet and can not refresh because of that.
=> Bugfix ContentEditController when saving new Field with localize:true 

assets/js/app/editor/Components/Image.vue, templates/_partials/fields/image.html.twig
This implements the extensions limitations e.g.:
```
image:
extensions: [ gif, jpg, png ]
```
=> image contenttype extensions config now works

composer.json, phpunit.bootstrap.php, phpunit.xml.dist, tests/php/DbAwareTestCase.php
Fixes https://github.com/bolt/core/issues/702
This doctrine bugfix actually made this issue visible :blush: 
https://github.com/doctrine/dbal/commit/a9b7bf855c6f391f96773f844d7158500394bcef#diff-7b1e94fb7dd408985f7b7973330dc2edR359
Here the issue was that dropping/creating the database is not transactional anymore. It was implicitly committing any open transaction on the underlying static connection from `dama/doctrine-test-bundle`. This is also mentioned in the readme of the bundle.
Before the doctrine bugfix this issue was hidden as the internal connection state (transaction nesting) was wrong.
So this PR fixes it by refactoring the database creation to be done **before** running any test. So there is no need anymore to do this within `setUp` or `tearDown`.
=> fix test database transactional isolation

Makefile
run `make start` result in error:
```
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 20480 bytes) in phar:///home/my-username/bin/composer.phar/src/Composer/Repository/ComposerRepository.php on line 339
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 20480 bytes) in phar:///home/my-username/bin/composer.phar/src/Composer/Repository/ComposerRepository.php on line 339
Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.make[1]: *** [Makefile:21: install] Error 255
make[1]: Leaving directory '/home/my-username/repo/php/bolt'
make: *** [Makefile:15: start] Error 2
```
=> Makefile: fixup composer Memory limit errors

assets/js/app/toolbar/Components/Toolbar.vue
Fixes #775 
There seem to be some [positioning issues](https://github.com/popperjs/popper.js/issues) with popper.js (the library Bootstrap uses to dynamically align dropdowns), so this disables dynamic positioning.
=> Fix jumping dropdowns

src/Controller/Backend/ContentEditController.php, src/DataFixtures/ContentFixtures.php, src/Entity/Field/CollectionField.php, src/Entity/Field/SetField.php
The fix in #795 creates a Set field, so that the standalone set is persisted.
This means, the Set field is also created as part of the Collection.
This introduces the issue that Bolt tries to treat the set inside the collection as a standalone field. In this case, by default the definition of the field is not set. Attempting to iterate over null in SetField::getValue() throws an exception.
Two possible solutions:
For now, the first one does the job.
=> Do not persist set field for set in collection

assets/js/app/common.js
From luxon doc:
toRelativeCalendar() - Returns a string representation of this date relative to today, such as "yesterday" or "next month".
toRelative() - Returns a string representation of a this time relative to now, such as "in two days".
=> replaces luxon toRelativeCalendar() with toRelative()

src/Entity/Field/SelectField.php, templates/helpers/_field_blocks.twig, templates/helpers/_fields.twig
Fixes #835 
You can now do things like: 
```twig
{% if field.contentSelect %}
{% setcontent selected = field.contentType where {'id': field.selectedIds} %}
{% for record in selected %}
<li><a href="{{ record|link }}">{{ record|title }}</a></li>
{% endfor %}
{% else %}
{% for key, value in field.selected %}
<li>{{ value }} <small>(key: <code>{{ key }}</code>)</small></li>
{% endfor %}
{% endif %}
</ul>
```
and 
```twig
{{ dump(field.value) }}
{{ dump(field.options) }}
{{ dump(field.selected) }}
```
=> Several improvements to how you can handle `type: select` fields in the Frontend

docker/php/Dockerfile
Currently, building the `php` docker image fails:
```
configure: error: unrecognized options: --enable-gd-native-ttf
ERROR: Service 'php' failed to build: The command [...] returned a non-zero code: 1
```
According to the [PHP manual](https://www.php.net/manual/en/image.installation.php) that flag has been "removed as of PHP 7.2.0". Removing it from the `Dockerfile` allowed me to build the Docker image without further errors.
=> Remove unsupported option from PHP Dockerfile

tests/behat/edit_record_1.feature
The test for the Embed field has always been a bit fickle on Travis. Sometimes it'd fail, but restarting it once or twice usually made it pass. However, on #905, I restarted it a dozen times without success. Let's disable it, until we can replace it with something more robust.
=> Disable Embed behat test

src/Utils/TranslationsManager.php, templates/_partials/fields/_base.html.twig
Makes the values an array ["etc"], rather than a JSON obect {"value":"etc"}
=> Persist collection items correctly

src/Entity/Content.php
Note: This is needed for exporting content.. In that case, we don't want to have markdown parsed, like we _do_ want in the API, for example.
=> Export fields as actual (not interpreted) values

config/bolt/contenttypes.yaml, src/Controller/Frontend/DetailController.php, src/Twig/ContentExtension.php
=> Implement `{{ record|current }}` Twig filter

src/Menu/FrontendMenuBuilder.php
- Recognizes `homepage: …` setting as correct link to homepage and generates correct url
- Relative links like `pages/` work correct now
=> Two fixes for Frontend menus

assets/js/app/editor/Components/Embed.vue, assets/js/app/editor/Components/File.vue, config/bolt/contenttypes.yaml, src/Configuration/Content/FieldType.php, src/Entity/Field.php, src/Entity/Field/CollectionField.php, src/Entity/Field/DateField.php, src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php, templates/_partials/fields/_base.html.twig, templates/_partials/fields/collection.html.twig, tests/e2e/edit_record_1.feature
Fixes #929 
Fixes #1035 
Examples:
```
type: text
default: "Hello, Bolt"
```
```
type: date
default: "yesterday"
```
```
type: image
alt: true
default:
filename: "foal.jpg"
alt: "This is a nice animal"
```
```
type: filelist
default:
0:
filename: "something.pdf"
title: "A file with something"
1:
filename: "another.pdf"
title: "This comes second"
```
```
type: collection
fields:
name:
type: text
age:
type: number
default:
0:
field: name
default: "Charlie Sheen"
1:
field: age
default: 54
```
=> Awesome default option

src/Entity/Field/CollectionField.php
When a collection with fields in the database exists, make sure not to break the backend if the collection is removed from contenttypes.yaml
=> Admin panel doesn't break when a collection is removed form contenttypes.yaml

assets/js/app/listing/Components/Table/Row/index.vue
Since slugs are localisable, pages with translatable slugs showed "Object object" for the hover on the listing page. This fixes it
=> Always show slug in listing title, even if translations are available

src/Extension/ExtensionRegistry.php
I can foresee a lot of people getting stuck when getting (the config of) extensions, if it requires the full name. For example, before you _had_ to do this:
```php 
/** @var ExtensionRegistry $extensionRegistry */
$extensionRegistry->getExtension('Bolt\\BoltForms\\Extension');
```
Now you can do this: 
```php 
/** @var ExtensionRegistry $extensionRegistry */
$extensionRegistry->getExtension('Bolt\\BoltForms');
// or even
$extensionRegistry->getExtension('BoltForms');
```
=> Allow getting extensions by partial name.

.eslintrc.js, assets/js/app/editor/Components/Embed.vue
eslint will fail on `console.log` but will allow `warn` and `error`.
=> Forbid console.log, but allow warnings and errors

templates/content/view_locales.html.twig
Localization page used to show the fields in a "random" (as persisted in DB) order.
It seems better to show them in the same order as they'd appear on the edit page.
=> Show localization page fields in same order as editing page

config/packages/translation.yaml, config/services.yaml, src/Configuration/Parser/ContentTypesParser.php, src/Kernel.php
=> Allow for adding locales to `config/services.yaml`

assets/js/app/listing/Components/Table/Row/_Meta.vue, assets/js/app/listing/Components/Table/Row/index.vue, assets/js/filters/string.js, assets/scss/layout/_admin.scss, assets/scss/modules/admin/_header.scss, assets/scss/modules/listing/row/row.scss, config/bolt/contenttypes.yaml, src/Configuration/Parser/ContentTypesParser.php, src/Controller/Backend/ContentOverviewController.php, src/Entity/Content.php, tests/php/Configuration/Parser/ContentTypesParserTest.php
- Show 'dateCreated' if no 'datePublish' is set
- Inverse order of title+excerpt and thumbnail (so it looks less wonky if _some_ records have no thumbnail)
- Increase margins and gap a tiny bit
- Don't output `&` as `&amp;`
- Improve default sorting order
=> A number of smaller fixes to overview pages

src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php
Ensures Imagelist and Filelist values work on `contents/1.json`, where the getApiValue on the images and files within the list is not called automatically by api-platform.
=> Make sure Imagelist and Filelist API values work on all endpoints

src/Entity/Content.php, src/Entity/Field.php, src/Event/Listener/ContentFillListener.php
All existing fields have the default locale as the first locale from the content definition.
Fixes issue with 'Untitled' record when 'en' is not a locale.
=> Set default locale for existing fields

src/Entity/ContentExtrasTrait.php, src/Twig/ContentExtension.php
A page with relations breaks if the relations' title is not available in 'en' locale, but it should not.
Instead, try to get a title for any of the defined content locales, in order to break less often (or not at all).
=> Content Extras gets any title, so that Relations break less often.

src/Event/Subscriber/TimedPublishSubscriber.php
For UX: If we don't have a DB set up yet, we'll now get a descriptive error, instead of a blank `500` server error.
=> Don't throw exception in listener for timedpublish

src/Configuration/Parser/ContentTypesParser.php, src/Storage/Directive/OrderDirective.php, src/Storage/QueryInterface.php, src/Storage/SelectQuery.php, templates/content/listing.html.twig, tests/php/Configuration/Parser/ContentTypesParserTest.php
In the backend no longer _always_ sort on `title`, but rather on the actual setting of `title_format` -> 
In frontend, ordering by a non-existent field, will produce debug output:
=> Make ordering in `{% setcontent %}` more robust

src/Entity/Content.php, src/Twig/JsonExtension.php
Pinging @I-Valchev : I had to make a modification to this. In the frontend you don't always want to include `definition` in the results. Can you verify it still works with the API like this? 
followup to #1164
=> Split off `get_definition` from `get_content` for Serializer purposes

config/bolt/contenttypes.yaml, src/Entity/Content.php, src/Entity/Field.php, src/Utils/ComposeValueHelper.php
- compose value uses less restrictive regex for matching field names (e.g. `_` is valid in yaml key names)
- compose value uses first contenttype locale, if field is translatable
- small fix to contenttypes.yaml since pages have `heading`, not `title`
=> Compose value works with allowed yaml key names + i18n

assets/scss/modules/editor/fields/_pre_postfix.scss
=> `postfix` and `prefix` need `display: block`

src/Entity/Field/CollectionField.php, src/Entity/Field/SetField.php, src/Utils/TranslationsManager.php
As with Imagelists and Filelists, make sure to return the values of the fields, not the object. Also, for collections, include the `name`, `type`, and `value`, as collections have different fields within them.
This PR is based on:
#1246 (for collections)
#1245 (for sets)
Fixes #1241
=> Collections and Sets in API

src/Entity/Field/SetField.php
Pretty sure I saw an issue about it today, but I can't find it :/ 
Basically:
`{{ set.title}}` does not work before this PR.
=> Access fields inside a set by their name

src/Kernel.php
=> Workaround for updating KnpLabs/DoctrineBehaviors, without breaking ` config/bundles.php` first

src/Controller/Backend/ContentEditController.php, tests/e2e/edit_record_2.feature
We can avoid flushing by removing the fields from the EntityManager _and_ from the current content, which allows the Preview to work as expected.
And fixes #1264
=> Fix Preview by removing EntityManager flush

templates/content/_fields.html.twig
Okay so an explanation about this...
We only want to get the the translated field if the field is translatable.
If it is not, we want the default value. By getting it explicitly, we make sure that even if `setLocale` was called somewhere earlier, we will override it.
Main cause for this is that the [DoctrineBehaviors translate method](https://github.com/KnpLabs/DoctrineBehaviors/blob/ebb188c6c29b09ede700e90f31201f6cefa2ab5b/src/Contract/Entity/TranslatableInterface.php#L33) does too much things at once. Sometimes you want to get the translated value _without_ changing the object. At other times, you want to _prepare_ the object for future use by changing its current locale.
=> Get correct field value depending on localization settings

src/Entity/Field.php, src/Twig/ContentExtension.php
🤦‍♂️
For months I worked under the assumption that non-translatable fields fallback to the default locale. But this is not how the doctrine-behaviors `translate()` method works. The fallback option is for `en_GB` to fallback to `en`, not to fallback to the `defaultLocale`.
My misunderstanding led to wrong implementation further down the line, which convoluted the problem further.
=> Field::getValue() returns defaultLocale value (if current locale value is empty empty) for non-localizable fields

src/Controller/Backend/ListingController.php
=> Mass delete on last page does not break. Content listing redirects to last page if requested page exceeds max

config/services.yaml, src/Api/Extensions/ContentExtension.php
API work is planned ahead for v4.3, however this seems important to fix now.
Fixes #1295 and #1296
=> API shows published and viewless: false content only

src/Api/Extensions/ContentExtension.php
These are some proposed changes to address #1295 and #1296 by ensuring users also can't access unpublished or viewless content through the field API either.
=> Api filter updates

src/Controller/Backend/FileEditController.php, templates/finder/_files_actions.html.twig, tests/e2e/filemanager.feature
=> Admin can duplicate a file

translations/messages.en.xlf
Fixes #1330
Turns out it's just the wording, not to do with using incorrect message.
=> Update content updated successfully message

src/Api/Extensions/ContentExtension.php
Doctrine does not work as expected if where clause contains an empty array condition.
This fixed it.
See [https://github.com/doctrine/orm/issues/3835](https://github.com/doctrine/orm/issues/3835)
=> API works if no viewless CTs exist

config/bolt/contenttypes.yaml, src/Configuration/Parser/ContentTypesParser.php, src/Twig/ContentExtension.php, src/Utils/ComposeValueHelper.php
=>  Improve `title_format` and add `excerpt_format` attribute in ContentTypes

src/Configuration/Config.php, src/Configuration/Content/FieldType.php, src/Configuration/Parser/ContentTypesParser.php, src/Entity/Content.php, src/Entity/Field.php, src/Event/Listener/ContentFillListener.php, src/Kernel.php, src/Repository/FieldRepository.php, tests/php/Configuration/ConfigTest.php, tests/php/Configuration/Parser/ContentTypesParserTest.php
So far all non-translatable fields were persisted with locale `en`.
In this PR, the fields are persisted with the provided `locale` from `services.yaml`
=> Persist non-translatable field with correct default locale

src/Entity/Field.php, src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php, src/Entity/ListFieldInterface.php
=> Wrap list fields with 1 element in array

assets/js/app/listing/Components/Table/Row/index.vue, assets/scss/modules/base/_tables.scss, assets/scss/modules/base/base.scss, assets/scss/modules/listing/row/row.scss, src/Controller/Backend/FilemanagerController.php, templates/finder/_files_cards.html.twig, templates/finder/_files_list.html.twig, templates/finder/_folders.html.twig, templates/finder/finder.html.twig, tests/e2e/filemanager.feature, translations/messages.de.xlf, translations/messages.en.xlf, translations/messages.nl.xlf
=> Update file listing screen: Lazy loading, paginator, other improvements

src/Entity/Content.php, src/Entity/Field/FileField.php, src/Entity/Field/ImageField.php
=> Image and File fields support twig empty test

src/Controller/Backend/ContentEditController.php
Fixes recent issue with saving some fields in the backend
=> Save non-localizable in correct default locale

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Image.vue, assets/js/app/index.js, assets/js/app/listing/Components/Table/Row/_Actions.vue, assets/js/app/patience-is-a-virtue.js, assets/js/app/sidebar/Components/Menu/_SubMenu.vue, templates/content/_buttons.html.twig, templates/content/listing.html.twig
=> Adding spinners and disabling buttons to indicate the user might have to wait a few seconds

src/Controller/Backend/ContentEditController.php, src/Entity/Field.php, src/Entity/Field/CollectionField.php, src/Entity/Field/SetField.php, src/Entity/FieldParentInterface.php, src/Entity/FieldParentTrait.php, src/Utils/TranslationsManager.php
Resolve rc18-20 issues with collections not being shown once saved.
=> Fix collections visibility

src/Entity/FieldParentInterface.php, src/Entity/FieldParentTrait.php
Works like this:
set `localize: true` only on the child elements and it still works.
Fixes 1/2 of #1432
=> Localize collections with easier contenttype config

src/Entity/Field/CollectionField.php, src/Entity/Field/FileField.php, src/Entity/Field/FilelistField.php, src/Entity/Field/ImageField.php, src/Entity/Field/ImagelistField.php, src/Entity/Field/SetField.php, src/Entity/ListFieldInterface.php, src/Entity/ListFieldTrait.php
=> Make sure list field |length filter works as expected

config/bolt/config.yaml, src/Entity/Content.php, src/Event/Listener/ContentFillListener.php
=> Update `getContentTypeName()`, add `getContentTypeSingularName()`

composer.json, config/bundles.php, config/routes/bolt.yaml, src/Kernel.php, symfony.lock
On the road to update to Symfony 5. See #1182
=> Fixing some deprecations

config/packages/framework.yaml, config/packages/twig.yaml, config/services.yaml, src/Controller/Backend/FilemanagerController.php, src/Controller/Backend/ListingController.php, src/Controller/ErrorController.php, src/Controller/Frontend/ListingController.php, src/Controller/Frontend/SearchController.php, src/Controller/Frontend/TaxonomyController.php, src/Event/Subscriber/ZoneSubscriber.php, templates/helpers/page_404.html.twig, templates/helpers/page_503.html.twig
=> Use new Symfony Error Controller, instead of Twig's old one.

composer.json, src/Twig/TextExtension.php, templates/content/_tabs.html.twig
=> Fix capitalisation in groups

src/Canonical.php, src/Configuration/Parser/ContentTypesParser.php, src/Controller/Frontend/DetailController.php, src/Repository/ContentRepository.php, src/Twig/ContentExtension.php, tests/php/Configuration/Parser/ContentTypesParserTest.php
Fixes #1483 
Fixes #1470
One outstanding issue:
```
termsandconditions:
path: /terms-and-conditions
defaults:
_controller: Bolt\Controller\Frontend\DetailController::record
contentTypeSlug: 'terms-and-conditions'
slugOrId: 31
```
The default slugOrId is set here.
Trying to get the `|link` on the `/terms-and-conditions` page breaks the url, because the ContentExtension::getLink always overrides the slugOrId param, hence the link becomes:
`/terms-and-conditions?slugOrId=someUnexpectedSlug`
where someUnexpectedSlug is the slug from the content.
I'm not sure how to fix this elegantly? @bobdenotter
=> Add ability to override routing with record_route

assets/js/app/toolbar/Components/Toolbar.vue, assets/scss/modules/admin/_toolbar.scss, src/Controller/Backend/DashboardController.php, src/Controller/Backend/ListingController.php, src/Controller/Frontend/DetailController.php, src/Controller/Frontend/SearchController.php, src/Controller/TwigAwareController.php, templates/_base/layout.html.twig, templates/content/listing.html.twig, templates/pages/dashboard.html.twig, tests/e2e/dashboard_globalsearch.feature, tests/e2e/record_listing.feature, translations/messages.en.xlf
=> Add Global search to backend

src/Canonical.php, src/Controller/Frontend/DetailController.php, src/Twig/ContentExtension.php, src/Utils/ContentHelper.php, tests/php/Twig/ContentExtensionTestCase.php
=> Make canonical record URL consistent across routes

composer.json
=> Don't "warm up" cache on `composer update`, to save time and prevent dreaded `ProcessTimedOutException` after 10 seconds..

src/Extension/ExtensionController.php, src/Extension/ServicesTrait.php
=> Ensure `$boltConfig` is set for Controllers in extensions

src/Controller/Backend/UserEditController.php, templates/users/listing.html.twig
=> User edit actions require valid csrf tokens

src/Command/SetupCommand.php
=> Better feedback on bolt:setup errors

src/Controller/Backend/ContentEditController.php
=> Fix issue with undefined index 0 for a select field inside a a set

src/Controller/Backend/UserController.php, templates/users/listing.html.twig
Fixes #1552 
Thing is though, current sessions is now only displayed for the users that are on the current paginated page.
Which I think makes sense?
=> Paginate users listing

templates/_partials/fields/date.html.twig
=> Don't break line on date field with valueonly

src/Twig/ContentExtension.php
With this PR you can now highlight words using both `Content`, as well as plain strings. 
Example: 
```twig
{{ "Cenasti in vita numquam bene, cum omnia in ista Consumis squilla atque acupensere cum decimano."|excerpt(30, focus = 'omnia') }}
{{ record|excerpt(100, focus = 'omnis') }}
```
Fixes #1590
=> Allow "focus" parameter for excerpts of plain strings

src/Twig/LocaleExtension.php, templates/_macro/_macro.html.twig, templates/_partials/fields/date.html.twig
=> Put `localedatetime` with previous format and deprecated notice. Use `localdate` with new format

src/Storage/SelectQuery.php
Remove unnecessary foreach{} loop on taxonomies which caused memory exhaustion on anyField search/setcontent #1541
=> modification following #1541

src/Storage/QueryParameterParser.php
=> Allow optional space in QueryParameterParser between operand and keyword

composer.json, config/packages/doctrine.yaml, phpstan.neon, public/theme/skeleton/custom/setcontent_1.twig, src/DataFixtures/ContentFixtures.php, src/Storage/Directive/OrderDirective.php
Fixes #1356 
Order by number field now casts the field value to int, so that the order by operates on numeric values.
=> Order by number field 

assets/js/app/editor/Components/Select.vue, src/Twig/ContentExtension.php, src/Twig/RelatedExtension.php, src/Utils/ContentHelper.php
=> Richer content format option

assets/scss/modules/base/_status.scss, config/bolt/config.yaml, src/Controller/ErrorController.php, src/DataFixtures/ContentFixtures.php, src/Twig/ContentExtension.php, src/Utils/ContentHelper.php
=> [WIP] Add support for "403 Forbidden" pages

src/Command/ExtensionsConfigureCommand.php
And also: Don't break on `php bin/console extensions:configure`, if the project has custom code in `src/` :-)
=> Allow extensions to have an `install` method, which is called on installation (to install assets, for example)

public/theme/skeleton/partials/_sub_menu.twig, public/theme/skeleton/partials/_sub_menu_header.twig, src/Configuration/Parser/MenuParser.php, src/Twig/CommonExtension.php, src/Twig/ContentExtension.php, src/Twig/FrontendMenuExtension.php, tests/php/Configuration/Parser/MenuParserTest.php, tests/php/Menu/FrontendMenuBuilderTest.php
Fixes #1655 
Use `|current` and not `.current`
=> [WIP] Use `current` filter to check if menu item is this page

src/Kernel.php
By making sure the auto-generated extension services are loaded first, we allow custom extension services + implementors to override them as they see fit.
=> Allow auto-generated extension services to be overridden

src/Entity/Field.php
=> Child fields can render html by default, without |raw filter

assets/js/app/editor/Components/Textarea.vue, config/bolt/contenttypes.yaml, src/Configuration/Content/FieldType.php, templates/_partials/fields/textarea.html.twig, tests/php/Configuration/Parser/ContentTypesParserTest.php
Fixes #1663 
Set textarea height like so:
```
height: 10 # 10 rows
height: 150px # 150 pixels
height: 50vh # 50% of viewport
```
=> Allow textarea `height` option

src/Entity/Field/EmbedField.php
`{{ record.embed.responsive|raw }}`
now works just with:
`{{ record.embed.responsive }}`
=> Use embed without `raw` filter

templates/_partials/fields/_base.html.twig
Well, that was easier than expected.
=> Allow for `variant: inline` for most fields

src/Command/ExtensionsConfigureCommand.php
Allows proper path splitting on Windows machines
Fixes #1715 
Changelog
---------
* Fixed: Path splitting on extensions:configure command (see #1715 )
=> Replaced hardcoded '/' by DIRECTORY_SEPARATOR

assets/js/app/confirmation.js, templates/_base/layout.html.twig, tests/php/Menu/FrontendMenuBuilderTest.php
This PR translates the bootbox modals.
'en' locale is used by default and if there is another locale set then that is the locale bootbox will use to show translated text in the modals.
More info here: http://bootboxjs.com/documentation.html#bb-function-setLocale
=> Use translated bootbox 

public/theme/skeleton/custom/setcontent_1.twig, src/Storage/SelectQuery.php
=> Make multivalue filter with content fields

src/Controller/Backend/AuthenticationController.php, src/Controller/Backend/ContentEditController.php, src/Controller/Backend/ContentLocalizationController.php, src/Controller/Backend/DashboardController.php, src/Controller/Backend/DatabaseIntegrityController.php, src/Controller/Backend/FileEditController.php, src/Controller/Backend/FilemanagerController.php, src/Controller/Backend/FixturesController.php, src/Controller/Backend/GeneralController.php, src/Controller/Backend/ListingController.php, src/Controller/Backend/LogViewerController.php, src/Controller/Backend/MediaController.php, src/Controller/Backend/MediaEditController.php, src/Controller/Backend/MenuPageController.php, src/Controller/Backend/OmnisearchController.php, src/Controller/Backend/ProfileController.php, src/Controller/Backend/UserController.php, src/Controller/Backend/UserEditController.php, src/Controller/Frontend/ListingController.php, src/Controller/Frontend/SearchController.php, src/Controller/Frontend/TaxonomyController.php, src/Controller/Frontend/TemplateController.php, src/Controller/TwigAwareController.php
=> Rename renderTemplate to render for consistency with AbstractController

src/Storage/SelectQuery.php
innerJoin replaced with leftJoin. "anyField" search/filter was only being performed on records which have Taxonomies assigned. LeftJoin resolves this problem,  searching/filtering records with "anyField" on all fields and taxonomies even if the record does not have any Taxonomies assigned.
=> modification to SelectQuery.php related to #1619

config/bolt/contenttypes.yaml
=> Update contenttypes.yaml comments documentation

src/Twig/ContentExtension.php
For example, when doing this: 
```twig
<p>{{ record.content|excerpt(200, false, search|default('')) }}</p>
```
Bolt would break with this error:
=> Prevent breakage when trying to excerpt a Field

assets/js/app/common.js, assets/js/app/editor/Components/Date.vue
Fixes #1743 
But I think this will also break the `pattern` attribute. Not that it makes sense for people to use `pattern` on a field that's not manually filled in..
=> Date field required updates validity when set

config/bolt/config.yaml, src/Configuration/Parser/GeneralParser.php, src/DataFixtures/ImageFetchFixtures.php
=> Unsplash images fixtures work even if ssl verification fails

config/packages/doctrine.yaml, src/Doctrine/Version.php, src/Entity/Field/NumberField.php, src/Storage/Directive/OrderDirective.php
=> Numeric order works on MySQL databases

src/Entity/Field/SlugField.php, templates/_partials/fields/slug.html.twig
Fixes #1785 
Issue is with cache (hence why it only happens _sometimes_ in production?). The method call is, for some reason, cached. Could be that on new objects it's cached the wrong way.
Calling the `definition.uses` in Twig directly resolves it.
I'm not super comfortable with the caching problem itself, however...
=> Avoid caching slug uses definition for new records

assets/scss/modules/editor/fields/_pre_postfix.scss
max-width was keeping pre and postfix from using 100% of the width of its container
=> Remove max-width

src/Controller/Backend/ContentEditController.php, src/Entity/Content.php, src/Twig/ContentExtension.php
=> Fix breakage in PROD for `type: select` fields

assets/scss/modules/editor/fields/_pre_postfix.scss, config/bolt/contenttypes.yaml, templates/_partials/fields/_base.html.twig, tests/e2e/kitchensink.feature
Additional change to #1796
```yaml
fields:
title:
type: text
class: large
required: true
pattern: ".{2,255}" # see: http://html5pattern.com/
error: "The Title field is required, and must contain at least 2 characters"
placeholder: "Placeholder for the title"
group: Text
postfix: |
This is an example of a longer "postfix". Simple text is capped at a reasonable width
to enhance legibility. Necessitatibus dolor corrupti assumenda placeat quia occati
aut. Facere porro placeat molestiae fuga. Laboriosam et asperiores atque impedit
dolorem dicta aut. Harum inventore ipsa voluptas consectetur quaerat eius ad.
<div class="alert alert-secondary" role="alert"><strong>Tip:</strong> You can even
use HTML in a prefix! Note that this one does take the full available width.</div>
```
=> Allow for more control over formatting of prefix and postfix

public/theme/skeleton/custom/setcontent_1.twig, src/Twig/ArrayExtension.php
Fixes #1805 
As it uses the `ContentHelper::get`, there are some limitations compared to ordering with `setcontent`. Most notably you can't order by taxonomies.
=> Make order filter work with `ContentHelper::get()` options

config/packages/doctrine.yaml
Fixes this: 
```
09:58:51 INFO      [php] User Deprecated: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number aware is deprecated and will be removed in Doctrine ORM 3.0.
```
=> Update `UnderscoreNamingStrategy` in `doctrine.yaml`

src/Entity/Field.php
This happens for fields that don't implement their own `__toString()` method, like `type: data`, or potentially Fields added by extensions.
=> Fix `Notice: Array to string conversion` in `Field.php` by ensuring  the  array is one level deep.

src/Utils/ContentHelper.php, src/Utils/Recursion.php
Now `title_format: '{title} pom {foo}'` will result in: 
Fixes #1825
=> Prevent recursion in `title_format`

src/Event/Subscriber/ContentSaveSubscriber.php
=> Clear menu caches on content delete. Log delete event.

.travis.yml
According to the [docs](https://docs.travis-ci.com/user/common-build-problems/), we can re-run failing commands within the same build, by default up to 3 times!
Hopefully, that makes behat behave!
=> Use `travis_retry` command on frequently failing behat tests

assets/scss/vendor/flatpickr/flatpickr.scss
Fixed the visiblity of time selection area when setting  ```mode: datetime``` on a date field.
=> Removed faulty definition to show timeSelection in Date Picker

assets/js/app/editor/Components/Collection.vue, assets/scss/modules/editor/fields/_collection.scss, assets/scss/modules/editor/fields/fields.scss, config/bolt/contenttypes.yaml, src/Configuration/Content/FieldType.php, templates/_macro/_macro.html.twig, templates/_partials/fields/_base.html.twig, templates/_partials/fields/_collection_buttons.html.twig, templates/_partials/fields/collection.html.twig, tests/e2e/edit_record_1.feature, tests/php/Configuration/Parser/ContentTypesParserTest.php, translations/messages.en.xlf
=> Collapsible collections

.travis.yml, config/bolt/config.yaml, ecs.php, src/Configuration/Parser/ContentTypesParser.php, src/Configuration/Parser/GeneralParser.php, src/Controller/Backend/Async/UploadController.php, src/Twig/HtmlExtension.php, templates/_macro/_macro.html.twig, templates/_partials/fields/collection.html.twig, templates/_partials/fields/file.html.twig, templates/_partials/fields/filelist.html.twig, templates/_partials/fields/image.html.twig, templates/_partials/fields/imagelist.html.twig, templates/helpers/_taxonomylinks.html.twig
Part of #1833
(don't mind the other commits.. I can't git 🙈)
=> Use configured `upload_location` for images and files in ContentTypes

ecs.php, src/Twig/ExtensionExtension.php
```
{% if 'bolt/core' is extension %}
<p>The extension is installed.<p>
{% else %}
<p>The extension is <strong>NOT</strong> installed.</p>
{% endif %}
```
=> Check if extension exists as a twig test

assets/js/app/editor/Components/Password.vue, src/Controller/Backend/UserEditController.php, templates/_partials/fields/select.html.twig, templates/users/edit.html.twig
Strictly speaking, 1 role should be more than enough given Symfony roles are hierarchical...
But at the same time, our `User` entity has multiple roles. + The `bolt/users` extension does not (yet?) use hierarchy.
In any event, it should not hurt that 1 user may have multiple roles.
=> Allow multiple roles to be selected for users

src/DataFixtures/ContentFixtures.php
=> Slugs in fixtures use the `uses:` attribute to make sensible slugs

assets/js/app/editor/Components/Collection.vue, assets/scss/modules/editor/fields/_collection.scss, package-lock.json, package.json, tests/e2e/edit_record_1.feature
See #1881 
What it looks like in Safari now:
=> Fix iffy details/summary marker 

translations/messages.de.xlf
The correct spelling is "Standard": https://www.korrekturen.de/beliebte_fehler/standart.shtml
=> fix(messages.de.xlf): Standart to Standard

src/Extension/ExtensionRegistry.php
This is useful if the base extension has a complex dependency graph.
You can configure the base extension class in `services.yaml` eg:
```yml
Bolt\Extension\SomeCompany\CoolExtension:
public: true
```
and it will then be constructed with dependencies resolved.
=> Try and resolve Extension classes from the DI container

assets/scss/modules/editor/fields/_collection.scss, templates/_partials/fields/_label.html.twig, tests/e2e/edit_record_1.feature
**before & after:**
**before & after:**
=> Collection updates

src/Controller/Backend/Async/FileListingController.php
Fixes #1910
get rid from hardcoded types in "Library" files dropdown (was missing .svg type)
add support to configure this types from config media types
``` yaml
accept_media_types: [ gif, jpg, jpeg, png, svg, pdf, mp3, tiff ]
```
=> add config media types to files list in dropdown

.github/workflows/code_analysis.yaml, .travis.yml
First pull-request for https://github.com/bolt/core/pull/1598#issuecomment-699467583
=> [CI] Move ECS from Travis to Github Actions

.github/workflows/code_analysis.yaml, .travis.yml, phpstan.neon
Follow up to https://github.com/bolt/core/pull/1912
=> [CI] Move PHPStan and Composer Validate from Travis to Github Actions

.github/workflows/code_analysis.yaml, .travis.yml, phpstan.neon
Follow up to https://github.com/bolt/core/pull/1916
=> [CI] Move console checks from Travis to Github Actions

src/Controller/Backend/FileEditController.php, templates/finder/_files_actions.html.twig
Fixes #1914 
- add path for subfolder to delete/duplicate action
- add path to return after action
- replace success notification label for duplicate action
=> fix edit file in File management subfolders

src/Repository/ContentRepository.php
Fixes #1920
if we allow numeric slug
I suppose to convert numeric slug to String couse not to brake repository method `findOneBySlug`
=> fix displaying page (singleton) by slug

src/Entity/Content.php
Fixes #1900 
Right now there's ways to get relations both in code (using the repository) or in twig using the various filters.
I'm not sure that's the _most desirable_ way to go, but as @simongroenewolt points out it's better to _not_ have them than return something wrong.
=> Exclude relations from `Content::toArray()`

templates/finder/editfile.html.twig, templates/pages/about.html.twig, templates/security/login.html.twig
As I looked through some of the TWIG templates my IDE (PHPStorm) marked some rather obvious HTML problems.
This PR cleans them up so at least these parts have valid HTML.
I did not add any containers or changed tags, I only moved mostly ending tags to the correct position or removed duplicate ending tags.
=> fix HTML DOM problems

README.md
Clicking on the build status in the old README.md just displayed a page of travis-ci.org showing, that the repository has been migrated to travis-ci.com
This PR adjusts the image and link in the README.md to the new travis-ci.com
Don't know why the image still says "build | failing" because all the builds are green but 🤷
=> Change travis-ci build status in README.md to travis-ci.com

src/Twig/RelatedExtension.php, templates/_partials/notification.html.twig
Before, when using `{% set foo = bar|related %}` was used and `bar` wasn't a Content, it'd fail like this: 
Now it shows a more helpful note:
=> Better feedback when `|related` and their ilk fail

src/Controller/ImageController.php
I tried to fix #1928, in the meantime i found out that a folder was created in the `thumbs` directory.
This folder will also be created if the image could not be created.
=> Dont create folders if the image can't be created

src/Controller/ImageController.php, src/Utils/ThumbnailHelper.php
- Do not split parameters using "x", could cause an other bug when the `location` or `fit` contains an "x".
- Do not use "parameter=value" syntax anymore.
- Assumes always sending both "WIDTH×HEIGHT" parameters.
=> Fix Buggy thumbnail url generation #1928

src/Extension/ExtensionRegistry.php
Before:
```
Bolt\BoltForms
Bolt\BoltFormsExtraRecipients # this is unreachable
```
=> Access extensions by name with full namespace

bin/composer-script/post-install-cmd.php, bin/composer-script/post-update-cmd.php, composer.json, symfony.lock
Implementing https://github.com/bolt/core/pull/1918#issuecomment-701460769
=> [composer] decouple post-install/update-cmd and skip run on CI

src/DataFixtures/ContentFixtures.php
Fix bug with ImageFixtures relative paths in windows #1978
=> Force path separator to / in ImageFixtures relative paths

src/Controller/Backend/ContentEditController.php, src/Demo/DemoContentValidator.php, src/Validator/ContentValidatorInterface.php, templates/content/edit.html.twig
NOTE: this PR is meant for discussion, see https://github.com/bolt/core/issues/1931 -- please don't merge it just yet.
These changes show a possible change to bolt to make it _support_ server side validation. This change is not meant to add validation itself to bolt (at the moment), just to make it possible for other developers without touching the core.
At the moment a class Bolt\Demo\DemoContentValidator is included to test the changes. Without using the suggested support structure it's hard to see if it is good enough.
Currently missing: field-level feedback in the editor.
=> [WIP] Feature/server side validation support

src/Doctrine/Query/Cast.php
Replace getDriver()->getName() call with getDatabasePlatform()->getName() to avoid [a deprecation in Doctrine](https://github.com/doctrine/dbal/pull/3558).
This returns `mysql` instead of `pdo_mysql` on MariaDB, at least, so the `mb_strpos` check should work just fine as-is.
=> Use DatabasePlatform instead of Driver to check for MySQL/MariaDB

src/Controller/Backend/ListingController.php, src/Controller/TwigAwareController.php, templates/content/listing.html.twig, translations/messages.en.xlf
Fixes #1965 
It also works for things which are not fields, e.g .status=published, but not through the UI.
It would be nice, in a future PR, to allow editors to filter by date, status, author... All things which are possible with this, _once the query params are set correctly_.
=> Filter by any field

assets/js/app/editor/Components/File.vue
When you upload a file that is too large you currently get an error showing [object Object], this change checks if there is a error message in that object, and displays that instead.
This fixes the [object Object] issue mentioned in https://github.com/bolt/core/issues/2000
=> Show actual error message from upload error response instead of [object Object]

assets/scss/modules/editor/fields/_set.scss, assets/scss/modules/editor/fields/fields.scss, templates/_partials/fields/_base.html.twig, templates/_partials/fields/set.html.twig
Fixes #2012 
Only affects sets that _are **not**_ in a collection.
Before:
After:
=> Show set as block

src/TemplateChooser.php
I wasn't able to set the listing template for a taxonomy in taxonomy.yml. Did some snooping in the code and found that this line was referring to the taxonomy config by the wrong identifier. Just changed it to the new identifier and I could now set the listing template in my taxonomy.yml.
Hope I'm putting the pr in the right place, followed the instructions from the Contributing documentation online. There was no issue so I just named it after what I did.
=> Changed name of generic taxonomy config file identifier

src/Storage/SelectQuery.php
Bugfix for: `{% setcontent entries = 'entries' where { categories: 'movies || news' %}`
=> Multivalue querying does not break for taxonomies

assets/scss/layout/_login.scss, config/packages/security.yaml, src/Form/LoginType.php, templates/security/login.html.twig
Follow up from #2007, using remember me as part of the form.
=> Use remember me field in login Symfony Form

src/Entity/Taxonomy.php
Following on from #2044, this prevents an exception being thrown when the `TaxonomyFillListener` has not been added to `services.yml`.  Any existing links will still generate as '/categories/something', for example, until the new listener is added.
@bobdenotter please review this before the next 4.1 release or it will break existing sites if `services.yml` is not updated.
=> Taxonomy singular slug fix part 2

assets/js/app/editor/Components/Collection.vue
Fixes https://github.com/bolt/core/issues/2045
=> fix duplicate html element ids in editor when specifying 2 or more collections in one content type

.travis.yml
I just checked the travis-ci.com build of the core because it was failing and I noticed some `build config validation` warnings.
This PR basically does exactly what is being explained in there.
We'll see if something breaks or not 😄
=> update .travis.yml according to info on travis-ci.com

src/Configuration/Config.php
Hello 👋 
When using custom `public_dir` folder, the config fails to parse the `theme.yaml` because the `PathResolver` is constructed with the default `$publicFolder` : "public"
I propose a fix by passing `$publicFolder` to `PathResolver`'s constructor .
=> Fix parsing of theme.yml

config/bolt/config.yaml
Allow rel attribute when sanitize HTML
Same proposition for Bolt 4 as made here --> https://github.com/bolt/bolt/pull/7885 for Bolt 3.7 
As the ckeditor link options have 'rel' tags in there 'advanced' tab it would be a good idea to allow rel tag by default/ Because it's a bit confusing for the user to be allowed to add the tag but to not store it in the database.
(see discussion here (talking about 3.7) --> https://boltcms.slack.com/archives/C094GL7ME/p1603187487310500)
=> allow rel attribute by default

composer.json, src/Twig/ContentExtension.php, src/Utils/Excerpt.php, src/Utils/Html.php
Before, excerpts could look like `This is an excerpt.            With two lines of text.                  Or even mo…`
In HTML this isn't a big deal, but it is when generating - say - SEO / OG tags. 
Edit: Github refuses to render the extra whitespace 🤦
=> Remove extraneous whitespace in excerpts

config/bolt/config.yaml, src/Controller/Backend/ContentEditController.php, src/Controller/ErrorController.php, src/Controller/Frontend/DetailController.php, src/Controller/Frontend/DetailControllerInterface.php, src/Controller/Frontend/ListingController.php, src/Controller/TwigAwareController.php
Hitting `/pages` for example will use the default locale, not the last used one.
=> Fallback to default locale when not explicitly given in URL

src/Kernel.php
Rename guesstimatePublicFolder() to getPublicFolder() and make the function protected. This way subclasses of Kernel can provide their own implementation, for example returning a hard-coded path.
=> Rename guesstimatePublicFolder() to getPublicFolder() 

src/Entity/Content.php, src/Utils/ContentHelper.php
Fixes issue with localized menu URI's not recognised as current. Credits to @nestordedios for finding and debugging this!
Also fixes issue with using `record.slug`. It used to return the _wrong_ locale.
=> Bugfix incorrect `|current` filter for localized menu items

assets/scss/init/_base.scss, assets/scss/modules/admin/_widgets.scss
Fixes this:
But keeps the padding in the card (where it was originally intended to be fixed).
=> Fix excessive padding in dropdowns

src/Menu/BackendMenuBuilder.php
The new support for extensions to insert menu items requires a change to the services.yaml - with a default set for the injected $extensionMenus the menu items will not appear when the configuration change hasn't been made, but it will allow the the site to keep working instead of throwing a big error.
=> add default value for $extensionMenus so bolt won't break when configuration hasn't been updated yet.

src/Twig/ContentExtension.php
This extension makes it easy to create links in Twig templates that use slugs, but based on the record ID.
Slugs may change over time, so hard-coding them in templates is undesirable. Much better to use ID values which are a much more stable identifier.
`{{ path('record', { 'contentTypeSlug' : 'pages', 'slugOrId' : 'some-great-document' }) }}`
Can now be written as 
`{{ path('record', { 'contentTypeSlug' : 'pages', 'slugOrId' : idToSlug(6) }) }}`
=> Lookup slugs from record IDs in Twig templates

src/Entity/Content.php
This is a fix for 'creating content from a 404 page', and the contenttype has no default_status set.
=> Fix: Set a default status for the `default_status`

templates/security/login.html.twig
=> Make Forgot password button less prominent than login

assets/js/app/editor/Components/Checkbox.vue, assets/js/app/editor/index.js, src/Entity/Field/CheckboxField.php, templates/_partials/fields/checkbox.html.twig
Fixes #2171 
It also changes some behaviour of the field value. Instead of being something _unexpected_ ("checked", "on", etc.) it will not be `true` (checked) or `false` (unchecked).
=> Checkbox value can be unset

src/Storage/QueryParameterParser.php
So, for example `{% setcontent any = 'page' where { 'slug' : '/' } %}
=> Allow '/' in setcontent where query

src/DataFixtures/ContentFixtures.php, src/Event/Listener/ContentFillListener.php
=> Fix for Argument 1 passed to Bolt\Repository\FieldRepository::findAllBySlug() must be of the type string, null given

src/Canonical.php, src/Utils/ContentHelper.php
This fixes an issue I had where the current locale was not picked up by homepage link generation.
Along the way I noticed that the fallback link generation ("Just use the current URL") always generated canonical links which sometimes led to links like "https://domain.tld/https://domain.tld" because it is used as a argument to setPath in getLink.
=> Fix homepage link generation, generate fallbacks as relative unless canonical

src/Controller/Backend/ContentEditController.php, src/Twig/ContentExtension.php
Fixes #2201 
PHP Arrays are **_THE WORST_**
`A key may be either an integer or a string. If a key is the standard representation of an integer, it will be interpreted as such (i.e. "8" will be interpreted as 8, while "08" will be interpreted as "08").` 🤦‍♂️
=> Don't break with `TaxonomyRepository::factory() must be of the type string, int given`

.github/workflows/behavioural_tests.yaml
Same as #2228 but for the features (next minor version) branch
=> Run E2E tests on lowest supported PHP version only [new features]

.github/workflows/behavioural_tests.yaml
Same as #2227 but for the bugfix branch
=> Run E2E tests on lowest supported PHP version only [bugfixes]

composer.json
=> Deprecate `bolt/binary-chromedriver` for `lanfest/binary-chromedriver`

src/Twig/ImageExtension.php
Fixes #1892 
Thanks @eduardomart and @nestordedios for finding and confirming the issue.
=> `|svg` filter uses correct path inside collection/set

config/bolt/config.yaml, src/Canonical.php, src/Configuration/Parser/GeneralParser.php, src/Controller/Frontend/ListingController.php
This PR fixes the following issues:
> Listing pages have different canonical when using singular or plural form: https://github.com/bolt/core/issues/2218
Example:
- Using `localization.remove_default_locale_on_canonical = true`
- Note how the URL contains the singular form but **the canonical is normalized to the plural form**
- Also the default locale (`en`) is removed (old behaviour)
> Add a new config option to tell Bolt if the canonical URL should force-prefix the default locale or not: https://github.com/bolt/core/issues/2219
Example:
- Using `localization.remove_default_locale_on_canonical = false`
- Note how the **default locale (`en`) is maintained on the canonical**
=> Canonical improvements

src/Entity/Content.php
With credits to @Dsduit for pointing this one out, so that _finally_ I could reproduce it reliably.
=> Show correct timezone for Content dates (createdAt, modifiedAt, publishedAt, depublishedat)

bin/composer-script/post-update-cmd.php, bin/composer-script/run.php
This is for `bolt/core`, but we can/should also do it in project. To do that, though, we'd need to revise `bolt/project` and move the post-update things in here, so we can version them.
=> Warn of outstanding migrations

config/bolt/menu.yaml, src/Menu/CachedFrontendMenuBuilder.php, src/Menu/FrontendMenuBuilder.php, src/Menu/FrontendMenuBuilderInterface.php, src/Menu/StopwatchFrontendMenuBuilder.php, src/Twig/FrontendMenuExtension.php, tests/php/Menu/FrontendMenuBuilderTest.php
Fixes #2222 
For example:
```yaml
main:
- label: Home
title: This is the <b>first<b> menu item.
link: homepage
class: homepage
- label: 
en: About
nl: Over
link: page/2
```
=> Localize menu with `{locale}: {label}` configuration

migrations/Version20201210105836.php
On an installation where I already ran `bin/console doctrine:schema:update` a while ago, the migration broke and was stuck from then on. 
by checking if the table and column don't exist yet, it'll continue and prevent breakage.
=> Make the migrations conditional

composer.json
Related to #2087 
I have no idea if 8.0 is downwards compatible with 7.0 nor do I have an idea how and where collections are used here.
It is just one step closer to allowing bolt to be installed with a PHP 8.0 CLI
=> allow tightenco/collect 8.0 to be installed

templates/content/listing.html.twig
@bobdenotter I noticed we sometimes calculate the number of records by multiplying the page * record listing thing
=> Show number of records on listing

src/Event/Listener/FieldFillListener.php, src/Utils/Sanitiser.php
Identical to #2198, but for the 4.1.x branch.
Fixes #2248
=> Allow `id` in sanitiser (purifier). Don't sanitise fields with `sanitise: false`

src/Doctrine/Query/Cast.php, src/Storage/Directive/OrderDirective.php
=> Fix casting exception with`orderby` when using MySQL/PostgreSQL

.github/workflows/a11y_tests.yaml, package-lock.json, package.json, tests/a11y/README.md, tests/a11y/pa11yci.json
Fixes #2084
A couple of notes about the current configuration:
- `threshold` in CI is set to 82, meaning tests will only fail the build if more than 82 errors are on a page. Right now, the most problematic page has 82 errors, hence if we start introducing new issues, tests will fail, but they won't fail for existing issues. That gives us time to fix the outstanding problems.
- `concurrency` is set to 1, meaning only one page at a time. This is so the first (authentication) test can be ran first, to the backend is accessible. Ideally, we'd be able to run the checks concurrently one day.
=> [WIP] Accessibility (a11y) automated tests

.github/workflows/a11y_tests.yaml, package.json, tests/a11y/README.md, tests/a11y/pa11yci.json
Fixes #2084 
Roughly speaking, this will make sure that the tests aren't failing for outstanding issues. But if we introduce new problems, they will most likely be flagged by pa11y and tests will fail. Seems like a good compromise as we undertake the big work of making the whole of Bolt accessible.
=> Run bolt in a11y tests

src/Event/Subscriber/LocaleSubscriber.php
I'm not even sure why this is broken in the first place 🤔
=> Use default locale when not explicitly stated

src/Controller/Backend/ProfileController.php, src/Event/Subscriber/LocaleSubscriber.php, src/Event/Subscriber/UserLocaleSubscriber.php
Fixes a bug that requires the user to re-authenticate in order to apply the locale settings.
=> Don't require user to re-authenticate after changing user locale

yaml-migrations/m_2021_01_15-doctrine.yaml
Adds the migrations for the recent fix for #2241 and an order change to `JSON_GET_TEXT`
=> Migrate `JSON_GET_TEXT` and `CAST` in `doctrine.yaml` since 4.1.11

src/Canonical.php
Fixes #2261
Examples that work with this PR:
```
/page/hello-world -> /hello-world
/nl/page/hallo-wereld -> /nl/hallo-wereld
```
To configure this, put 2 routes in `routes.yaml`:
```yaml
content_seo_locale:
path: /{_locale}/{slugOrId}
methods: [GET|POST]
defaults:
_controller: Bolt\Controller\Frontend\DetailController::record
content_seo:
path: /{slugOrId}
methods: [GET|POST]
defaults:
_controller: Bolt\Controller\Frontend\DetailController::record
```
**Note: Naming is important here.** The localised route should be `{{ routeName }}_locale`, whereas the non-localised (generic) route should be `{{ routeName }}`. 
Then, for each Content Type that should have pretty URLs, set `record_locale` to `{{ routeName }}_locale`. This way, Bolt's existing URL shortcut for the default locale will be …
=> Bolt generates pretty URLs without `contentTypeSlug` in path or query params

composer.json
Temporary workaround, until we fix #2335 properly.
=> Pin API-platform to `2.5.*` for now

config/bolt/permissions.yaml
Update config in permissions.yaml so it will be (more or less) backwards compatible. Use only ROLE_ADMIN and ROLE_EDITOR in config to keep things simple, commented content-type specific configuration. Updated roles available in editor.
=> update/simplify permissions.yaml

src/Entity/Content.php
Fixes an issue where a new checkbox added to an existing record is always (wrongly) set to true.
Fixes the `default` value option for a checkbox to work.
=> Fix new checkbox value on existing records

src/Entity/Field/SelectField.php
=> Selects with `multiple: true` always have an array value

src/Twig/ArrayExtension.php
Make sure that dates are sorted as DateTime objects, not strings.
=> Fix `|order` filter by date

src/Controller/Frontend/TaxonomyController.php, src/TemplateChooser.php
=> Fix taxonomy `listing_template` inconsistency. Fix the canonical for `slug` and `singular_slug`

src/Entity/Field/SetField.php
=> Don't show old fields in a `set` if they're removed from the definition

public/theme/skeleton/custom/setcontent_1.twig, tests/e2e/setcontent.feature
Turns out that a lot of the times there's dumps in the Symfony debug toolbar that contain the `[no]` from the Twig template, which tricks the tests to assume there's an error.
=> Use more specific selector for the `setcontent` [no] test page

src/Controller/Backend/Async/FileListingController.php
Fixes #2412 
Credits due to @nestordedios for working out a solution with me :-)
=> From Library button on Windows generates the correct URL

assets/js/app/editor/Components/Embed.vue, templates/_partials/fields/embed.html.twig, translations/messages.en.xlf
=> Make Embed fields accessible

src/Repository/ContentRepository.php
Hey folks!
This is a fix for the issue I described in #2427.
I added search term encoding & escaping to match the format of the content in `bolt_field_translation`.
There doesn't seem to be any tests for this repository/method, but I tested the change on a Bolt project with: 
- the examples mentioned in the issue
- other strings with accented/special characters
- regular strings without special characters
- email adresses
- numbers
... and they all worked fine. 
If there are tests set up for this and I just missed them somehow, just let me know and I'll take the appropriate steps.
Cheers!
=> Allow search queries containing special characters (fix for #2427)

src/Menu/FrontendMenuBuilder.php
=> Identical record slugs in `menu.yaml` don't create conflicting URIs

composer.json
The main issue, see discussion https://github.com/api-platform/core/issues/3349
Fixed by locking `"api-platform/core": "2.5.3"`, which then causes:
See https://github.com/api-platform/core/issues/3683
=> Temporary version lock for `api-platform` bug

templates/helpers/_pager_basic.html.twig
=> Set correct classes and disabled states for the `_pager_basic.html.twig` pager

src/Twig/ContentExtension.php
=> The `|excerpt` filter returns the excerpt in the correct locale

src/Controller/Backend/ContentEditController.php, src/Entity/Field.php, src/Event/Listener/FieldFillListener.php
Stealing @I-Valchev 's thunder here, from #2483 
> Fixes a few things related to the preview, among which:
>
> -    the allow_twig
> -    makes sure the record global variable is set in the preview
> -    makes sure there's minimal differences between the preview and the actual record handling
> 
> LESS CODE IS MORE 🚀
=> Fix the `allow_twig` option to work in the preview

assets/scss/modules/base/_status.scss
**Before:**
**After:**
Bit of an ugly SCSS implementation, but it makes sure it's done across the board and keeps simple `status is-published`, `status is-held`, etc. classes.
=> Use form and shape in addition to colour for content statuses

assets/js/app/editor/Components/Password.vue, assets/scss/modules/user/user.scss, templates/users/_form.html.twig
And fixes a glitch where clicking the eye icon moved it a couple of pixels.
=> Add `copy to clipboard` for suggested password. Fix view password glitch

assets/js/app/editor/Components/Image.vue, assets/scss/modules/admin/_menupage.scss, assets/scss/modules/admin/admin.scss, templates/content/_buttons.html.twig, templates/pages/menupage.html.twig, tests/e2e/users.feature
- Image field preview is full-width on mobile, as a two-column layout with the input.
- Don't repeat the "Save/Preview" buttons twice on mobile
- Center and clean up the menupage buttons on mobile
=> Minor mobile improvements to content editing

.github/workflows/behavioural_tests.yaml, .github/workflows/code_analysis.yaml, .github/workflows/unit_tests.yaml, behat.yml, bin/upload-textfiles, composer.json, src/Command/ImageTrait.php, src/Command/ListUsersCommand.php, src/Doctrine/JsonHelper.php, src/Entity/TranslationInterface.php, src/Menu/BackendMenuBuilder.php, src/Utils/FlagMaster.php, tests/php/Security/LoginFormAuthenticatorTest.php
=> PHP 8.0 support for Bolt 5.0

src/Security/LoginFormAuthenticator.php
Don't show that a username is "guesstimated" by switching between `Username not found` and `Invalid credentials` exception. Instead, only ever show `Invalid credentials` for credentials issues.
=> Only show generic `Invalid credentials` error if error is credentials related

src/Extension/BaseExtension.php, src/Extension/ExtensionInterface.php
Prevents: 
```
Return value of Bolt\Extension\BaseExtension::getComposerPackage() must be an instance of Composer\Package\CompletePackage or null, instance of Composer\Package\AliasPackage returned
```
=> Use `CompletePackageInterface` in BaseExtension

composer.json, public/theme/skeleton/partials/_recordfooter.twig, src/Controller/TwigAwareController.php, src/Event/UserEvent.php, src/Extension/BaseExtension.php, src/Twig/ContentExtension.php, src/Twig/LocaleExtension.php, src/Twig/TranslatableExtension.php, templates/content/_fields.html.twig, templates/helpers/_field_blocks.twig
If this is accepted, we need to fix https://github.com/bolt/newswidget/issues/6
=> Remove 4.x deprecations

src/Twig/LocaleExtension.php
=> Allow parsing of `localdate`s like `now` or `today + 1 week, 21:00`

src/Controller/Frontend/DetailController.php
=> Show `404` instead of Exception when missing secret

assets/js/app/toolbar/Components/Toolbar.vue, templates/_base/layout.html.twig
This PR is part of #2429 .
It adds a label to the search input field visible only to screen readers .
=> Improve backend search box accessibility

templates/finder/_files_list.html.twig
Fixes #1997.
The button contrast seems to be already fixed. This PR only fixes the contrast of the text. See screenshot.
Before:
After:
=> Improve contrast ratio in filemanager

src/Entity/Field/SelectField.php, src/Kernel.php, src/Twig/ContentExtension.php
Two new options:
**Option 1: Static callable**
Example `contenttypes.yaml` configuration:
```yaml
books:
type: select
values: App\Books::getOptions
```
Allows you to implement an `App\Books` class like so (where the `$field` argument is optional):
```
<?php
declare(strict_types=1);
namespace App;
use Bolt\Entity\Field\SelectField;
class Books
{
public static function getOptions(SelectField $field): iterable
{
return [
'Animal Farm',
'1984',
];
}
}
```
**Option 2: Callable as a Symfony service (with autowiring and autoloading)**
Example `contenttypes.yaml` configuration:
```yaml
books:
type: select
values: App\Books
```
Allows you to implement an `App\Books` class like so (where the `$field` argument is optional):
**Important**: the `App\Books` service **must** explicitly be …
=> Allow `SelectField` options from callables and services

src/Doctrine/JsonHelper.php
=> Don't throw `Argument 2 passed to Bolt\Doctrine\JsonHelper::wrapJsonFunction()` for checkboxes

src/Widget/BaseWidget.php, src/Widget/BoltHeaderWidget.php, src/Widget/Injector/HtmlInjector.php, src/Widget/ResponseTrait.php, src/Widget/SnippetWidget.php, src/Widget/WidgetInterface.php, src/Widgets.php, tests/php/Widget/WidgetsTest.php
Fixes #1585
It also keeps a single `$target` class variable, for ease of use and backwards compatibility. Apart from that, all other handling should be handled as an array of targets.
=> Support multiple targets for widget, keeping `$target` too

composer.json
I'm not sure if PSR-7 is actually used by this bundle, but that is the only major change between v5 en v6 of `sensio/framework-extra-bundle` (see https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/710 / https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/CHANGELOG.md). 
It seems to work fine for me when forcing composer to install v6.1.2.
=> Allow sensio/framework-extra-bundle version 6

assets/js/app/listing/Components/Table/Row/_Meta.vue, assets/scss/modules/listing/row/row.scss
Before: 
After: 
It would be better if it were dynamic, but that might have downsides as well (like, columns shifting). This fix makes it better, with low impact.
=> Fix a CSS quirk in listing overview pages

assets/scss/modules/listing/row/row.scss, config/bolt/config.yaml, src/Canonical.php, src/Event/Subscriber/WidgetSubscriber.php, src/Widget/CanonicalLinkWidget.php, templates/widget/canonical.html.twig
I added a option to set you own canonical template.
I also added the option to get a relative path passed to the template, which makes it much more flexible.
I think this could be useful to others too.
Let me know if anything could be improved, I look forward to any feedback.
=> Added option to use your own canonical template

composer.json
Fixes `Warning: count(): Parameter must be an array or an object that implements Countable in /[...]/bolt/core/vendor/friendsofphp/php-cs-fixer/src/AbstractProxyFixer.php on line 73`
=> Fix ecs breakage with `friendsofphp/php-cs-fixer`

src/Command/CopyThemesCommand.php, src/Extension/ExtensionRegistry.php
When running `php bin/console bolt:copy-themes`, it will _also_ copy any themes that are installed as extensions.
@bobdenotter It _should_ work as-is, but I wasn't able to test it because of version constraints. Maybe you have an idea of how to verify that it works?
=> Copy packaged themes in `bolt:copy-themes` command

config/bolt/contenttypes.yaml, src/Configuration/Parser/ContentTypesParser.php, src/Controller/Backend/ContentEditController.php, src/Factory/RelationFactory.php
This PR fixes three issues related to Relations:
- Default to `required: false`, since it makes most sense if you can _clear_ a Relation.
- Allow deletion of a Relation from either side in the Backend
- Fix logic error in `getFromMemory` in `RelationFactory`
=> Several fixes for handling Relations

migrations/Version20201210105836.php
by specifying a primary key
This should fix https://github.com/bolt/core/issues/2569
This has not been tested on sqlite!
=> fix issue with migration that wouldn't run on MariaDB 10

src/Utils/LocaleHelper.php
It turns out that `getCurrentLocale` can be pretty inefficient, especially when a page has a lot of fields and/or relations. Every time _any_ field is fetched, like `{% record.title %}`, the `currentLocale` is checked, triggering a database lookup. 
See these screenshots from a real-world site, where a page has 180 related records. Before: 
After:
In this out-of-the-ordinary case, performance increases by a factor of 60. 
On 'regular' sites, performance gains are around 10 to 15% for detail pages.
=> Performance boost: Keep in-memory copy of `currentLocale`

src/Twig/ArrayExtension.php
=> Fix `|filter` and `|order` chaining returning no results

.github/workflows/behavioural_tests.yaml, bin/upload-textfiles
We pin Chromedriver to `90.something`, because `91` _appends_ text when using `.setValue()` instead of replacing it.
=> Pin Chromedriver to version 90.x 

composer.json
Fixes the issue where some people bumped into upgrade problems with vague descritpions, because they were still on composer 1. 
If this is you, please upgrade to composer 2, by running `composer selfupdate --2`. 
The main difference you'll notice is that Composer 2 is an order of magnitude faster than Composer 1 is.
=> Add restriction for (global) Composer 2 to `composer.json`

src/Command/ExtensionsConfigureCommand.php
Fixes #2615 
@LordSimal I'd also advise renaming it to `services.yaml` (note the A), that way it will work for people with `4.1.21` as well :-)
=> `extensions:configure` accepts both `.yaml` and `.yml` for config, routes and services in extensions

src/Kernel.php
=> Fix error in custom code producing seemingly unrelated message. Catch `LoaderLoadException` instead of `Throwable`

src/Command/ExtensionsConfigureCommand.php
=> Pass around `BaseExtension` instead of string in `ExtensionsConfigureCommand`

composer.json
For context: 
https://symfony.com/blog/cve-2021-32693-authentication-granted-to-all-firewalls-instead-of-just-one
https://github.com/symfony/symfony/commit/3084764ad82f29dbb025df19978b9cbc3ab34728
=> Don't allow `symfony/security-http` 5.3.0 and 5.3.1

src/Controller/TwigAwareController.php, src/Extension/BaseExtension.php, src/Widget/BaseWidget.php
One of our Symfony bundles that we're testing on Bolt uses a custom Twig loader.
This results in `$this->getTwig()->getLoader()` code used in Bolt in several places to return an instance of `Twig\Loader\ChainLoader` instead of `Twig\Loader\FilesystemLoader` making the code in question fail in Bolt, which results in Bolt not being able to find any of its templates.
This fix adds support for `ChainLoader`, which basically iterates over any Twig loader in the chain loader, and if it is an instance of `FilesystemLoader`, does what Bolt did previously (adds or prepends a new path, based on context).
Thanks to @ilukac for discovering the cause of the issue.
=> Support Twig chain loaders if available

src/Controller/Backend/Async/UploadController.php, src/Factory/MediaFactory.php
For example, you have this: 
```yaml
accept_file_types: [ …, mp4, …]
accept_media_types: [ gif, jpg, jpeg, png, svg, pdf, mp3, tiff, avif, webp ]
```
Uploading an `mp4` into a `type: file` field _should_ work, but it doesn't, because it doesn't generate a Media Entity. This PR fixes that.
=> Fix incorrect error when uploading an allowed filetype, that isn't an image

src/Controller/Backend/AuthenticationController.php
input `admin@example.org` becomes:
=> [4.x] Simplify, don't mangle username on incorrect input for Login

assets/js/app/editor/Components/Select.vue, src/Configuration/Content/FieldType.php, templates/_partials/fields/select.html.twig, tests/php/Configuration/Parser/ContentTypesParserTest.php
Fixes #2720 and makes `autocomplete: true` the default
=> Fix issue with incorrectly named `autocomplete` option

assets/js/app/sidebar/index.js, templates/_base/layout.html.twig, tests/e2e/record_listing.feature
This will cause the 5.0 cypress tests to fail. Will fix separately.
Fixes #2735
=> Fix `group: sidebar` conflicting with Bolt's sidebar

assets/js/app/editor/Components/Filelist.vue, assets/js/app/editor/Components/Imagelist.vue, src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php
=> `imagelist` and `filelist` fields can be emptied

assets/scss/init/_variables.scss
Changing orange to red, because it was the only accessibility-compliant color that I could find 🤷‍♂️
=> Update the warning color to a11y compatible

tests/cypress/integration/record_listing.spec.js
=> Fix tests following `sidebar` rename to `bolt--sidebar`

src/Twig/ContentExtension.php, src/Twig/FieldExtension.php
=> Exclude partials in the `templateselect` default filter. Move methods to `FieldExtension`

templates/_partials/fields/imagelist.html.twig
The label was missing in `imagelist.html.twig` file. 
Fixes #2721
=> Fix From URL label in an Imagelist's Image Field upload button

assets/js/app/editor/Components/Select.vue, templates/_partials/fields/select.html.twig
Allows the number of options displayed in select fields to be set by the limit value in the contenttypes.yaml
=> Unlimited select field options

src/Repository/ContentRepository.php
=> Search now also finds words with special characters, like `büßen`

bin/composer-script/CreateProjectScript.php, bin/composer-script/PostInstallScript.php, bin/composer-script/PostUpdateScript.php, bin/composer-script/PrePackageUninstallScript.php, bin/composer-script/ProjectEventHandler.php, bin/composer-script/Script.php
The important part of this PR is: 
```php
// Depending on the context, we're using either Symfony/Process 2.8.52 (bundled with composer 2.1.x)
// or Symfony/Process 5.3.x (if we're using our own). The signature of the Constructor changed
// from: `public function __construct(string $commandline, …)`
// to:   `public function __construct(array $command, …)`
// We'll have to attempt one, and otherwise fall back to the other.
try {
$process = new Process($command);
} catch (\TypeError $e) {
$process = new Process([$command]);
}
```
This was fun to figure out! (not)
=> Workaround for constructor signature change in Symfony/Process

src/Controller/Backend/ContentEditController.php, src/Controller/Frontend/PreviewController.php, src/Controller/TwigAwareController.php
Fixes an issue causing the backend locale to be interpreted as the frontend locale during preview, rolls back #2772.
Good example of how refactoring the `ContentEditController` will be good!
=> Preview is frontend zone, fix for viewing content in another locale

bin/composer-script/CreateProjectScript.php
These files are now directly in https://github.com/bolt/project as `.env` and `.env.local`
=> Remove `copyEnv` from `post-create-project` script

bin/console, phpstan.neon, src/Command/ImageTrait.php, src/Command/InfoCommand.php, src/Controller/Backend/GeneralController.php, templates/pages/about.html.twig
Try to set `memory_limit` on the CLI to help out with memory limits, to turn this: 
into: 
Also show the memory limit on `/about` and `bin/console b:i`:
=> Show `memory_limit` and attempt to set in on CLI

src/DataFixtures/UserFixtures.php
Instead of removing the dummy users (#2813) the status is set to disabled by default. Only admin's status is set to enabled so it can access the backend.
=> Addressed remove dummy users issue.

assets/js/app/editor/Components/Number.vue, templates/_partials/fields/number.html.twig
Id was missing for the integer and float field which broke both of the labels.
=> Fix missing id's for integer/float field

config/packages/doctrine.yaml, src/Doctrine/Version.php, src/Storage/FieldQueryUtils.php, src/Storage/SelectQuery.php, yaml-migrations/m_2021-09-16-doctrine.yaml
Fixes #2806 select for MySQL where we can use `JSON_SEARCH`.
Doesn't yet fix the multiselect, but there's the groundwork. Not yet sure how to best parse the multiple expression...
=> Fix querying selects and multiselects

composer.json, src/Storage/Directive/PrintQueryDirective.php
Fixes #2807 
For example: `{% setcontent pages = 'pages' where { 'test': '[123,456]'} printquery %}`
=> Don't break `printquery` on array values

src/Command/AddUserCommand.php
When providing a complete add-user command (`bin/console bolt:add-user --admin admin admin admin@localhost Admin`), the `interact` method is not called, resulting in the admin and developer options to be completely ignored. By detecting their presence in the `execute` method as well, the user is created correctly.
Workaround till merged/released is to use the `bin/console bolt:add-user --role=ROLE_ADMIN admin admin admin@localhost Admin` with the role argument instead.
=> Ensure admin/developer option is respected

src/Storage/SelectQuery.php
Fix setcontent clauses like this:
```
{% setcontent stickyNewsItem = 'news' where { sticky: true } returnsingle %}
```
Where `sticky` is a Checkbox field (`type: checkbox`). 
This only showed up on MySQL 5.7 and MySQL 8.
Fixes #2593
Fixes #2838
Fixes part of #2748
Fixes #2547
=> Fix `{% setcontent where { … } %}` for Checkbox fields

src/Storage/SelectQuery.php
Fixes #2841
Partially fixes #2748
=> Fix Multiselect in setcontent

config/packages/security.yaml, config/services.yaml, src/Form/LoginType.php, translations/messages.en.xlf, translations/messages.nl.xlf
Note, the diff on `src/Form/LoginType.php` seems large, but apparently every line in that file was indented.
=> Enable 'Remember me' by default, and make duration configurable

src/Controller/Frontend/DetailController.php, src/Controller/Frontend/PreviewController.php
Sometimes clients or editors paste links to specific pages with a URL they've copy/pasted from a preview. Like `https://example.org/preview/123`. 
This will give an error like: 
This PR allows a `GET` request to that page (assuming it's published, similar to the existing "detail view")
=> Redirect 'GET on Preview' link to edit page

public/theme/skeleton/partials/_image.twig
If you create a field with an empty alt attribute it returns an error in the standard skeleton theme
=> An empty image alt made the page throw an error

src/Menu/BackendMenuBuilder.php
Fixes #2923 and makes the icon in the menu consistent with the icon on the Other content page
=> Fix the Other Content menu icon

src/Command/SetupCommand.php
The "--if-not-exists" is on a nested array and ignored by the doctrine command for database creation.
=> fix(setup-command): skip creating the database if it already exists

src/Configuration/Config.php
These changes use $_ENV instead of getenv to retrieve environment variables.
Fixes #2909
Changelog
---------
* Fixed: Dynamic configuration values are not resolving correctly (see #2909)
=> [#2909] fix(configuration): use environment variables into config settings

migrations/Version20211123103530.php
Introduced intentionally in #2912. This fixes #2912 as a BC change.
=> Drop `UNIQUE` constraint for bolt_user_auth_token.user_id

templates/_partials/fields/select.html.twig
Fixes #2975 
It seems only the `"wide-options"` class was being added by default. I've kept this class to be rendered since there is some CSS targeting that class.
=> Make it possible to add custom class in Select field

Makefile, docker-compose.yml
These changes skip database creation if exist for make targets and avoid node 17 openssl3 issues with webpack with docker.
Changelog
---------
* Fix: Fix node image version for docker to avoid node17 openssl3 issues with webpack [(nodejs 17: digital envelope routines::unsupported)](https://github.com/webpack/webpack/issues/14532#ref-commit-abc9d51)
* Chore: Skip database creation if already exist into make targets
* Chore: Start automatically webpack encore dev for watching files into node docker container
=> chore(local-stack): improve make targets and avoid node17 issues for docker

config/bolt/config.yaml, config/services.yaml, src/Cache/CachingInterface.php, src/Cache/CachingTrait.php, src/Cache/CanonicalCacher.php, src/Cache/ContentToArrayCacher.php, src/Cache/RelatedOptionsUtilityCacher.php, src/Cache/SelectOptionsCacher.php, src/Canonical.php, src/Menu/BackendMenu.php, src/Menu/FrontendMenu.php, src/Twig/FieldExtension.php, src/Twig/JsonExtension.php, src/Twig/RelatedExtension.php, src/Utils/RelatedOptionsUtility.php
Enhances #2957
Replaces #2887, #2890
=> Improve caching

composer.json
Symfony/flex v2 should be compatible with Bolt, so lets allow it. See https://github.com/symfony/flex/releases/tag/v2.0.0 for the release notes, it is basically a versions which only support composer 2.1+ & PHP 8.0+.
=> Allow symfony/flex v2

templates/_macro/_macro.html.twig, templates/_partials/fields/_base.html.twig, templates/content/_relationships.html.twig, templates/content/_taxonomies.html.twig
=> Allow prefix and postfix text on relationships and taxonomies input field

src/Twig/ArrayExtension.php
If you filter the results from a setcontent query it returns an array with the records but the normal pager puts these records on the page they used to be. This paginate function will group these records to the same page
=> Add new paginate function for arrays

assets/js/app/editor/Components/Date.vue, src/Storage/SelectQuery.php
This (#2993) bug has a bunch of things that nee to be done:
Fixes #2993
=> Date issues in Bolt 5

src/Storage/SelectQuery.php
=> Allow Select fields with `JSON_SEARCH` to filter multiple values

bin/composer-script/CorePostUpdateScript.php
Fixes #3012 
But...unit tests making a DB connection 😐 
Besides the code is pretty complex, which is also not in the spirit of unit tests:
https://github.com/bolt/core/blob/master/tests/php/Factory/RelationFactoryTest.php#L89-L105
I think we need to refactor this.
=> Fix php unit relation test

config/packages/security.yaml, phpstan.neon, src/Security/AuthenticationEntryPointRedirector.php, templates/security/login.html.twig, yaml-migrations/m_2021-12-10-security_1.yaml
=> Redirect to login page if unauthenticated

config/bolt/permissions.yaml, public/theme/skeleton/custom/setcontent_1.twig, src/Controller/Backend/ContentEditController.php, src/DataFixtures/UserFixtures.php, src/Doctrine/Version.php, src/Storage/Directive/OrderDirective.php, src/Storage/FieldQueryUtils.php, src/Twig/ContentExtension.php, templates/_macro/_macro.html.twig, templates/content/_taxonomies.html.twig, tests/cypress/cypress-dev.json, tests/cypress/integration/chief_editor_permissions.spec.js, tests/cypress/integration/setcontent.spec.js
=> Port the has sortorder for taxonomies 3001 (#3016)

src/Security/LoginFormAuthenticator.php
=> Make `LoginFormAuthenticator` compatible with Symfony 5.3

templates/users/listing.html.twig, translations/messages.en.xlf, translations/messages.nl.xlf, translations/security.nl.xlf, translations/validators.nl.xlf
Fixes #3047 
This PR adds a new translation label and translations for the heading Current sessions and updates the dutch translations of some text in this page.
=> Users overview page dutch translations

Makefile
Hello! 
Some cleaning was made in the `db-*` and `docker-db-*` sub-tasks, but an old one is still called, breaking the `make docker-install` procedure.
This fixes it!
=> Fix wrong subtask called in makefile for docker

assets/js/app/editor/Components/Date.vue, src/Storage/SelectQuery.php, tests/cypress/integration/edit_record_1_field.spec.js
Hello! 
The recent changes to the format handled by date & datetime fields introduced a few bugs : 
Having the `h` format instead of `H` for hour will :
- make default hour stored for date fields as `12:00` 
- make default hour for query comparison as `12:00` (e.g. when using `where { date: '>yesterday' }`)
- only store the hour in a range between 0 and 12 on a `datetime` field when you type a PM hour (with or without the AM/PM selector) 
Fixes #3024
=> Fix date format to save PM time

assets/js/app/editor/Components/Select.vue, src/Cache/RelatedOptionsUtilityCacher.php, src/Entity/Field.php, src/Entity/Field/SelectField.php, src/Twig/ContentExtension.php, src/Twig/FieldExtension.php, src/Twig/RelatedExtension.php, src/Utils/RelatedOptionsUtility.php, templates/_partials/fields/select.html.twig, templates/content/_relationships.html.twig, templates/content/_taxonomies.html.twig
- have a required select field;
- select field must not pre-select any option;
- user must deliberately choose an option;
Current Bolt behaviour automatically selects first option if field is required.
Add a configuration setting called `allow_empty` which enables developer to force an empty option for select control, even when control is required.
`allow_empty` setting is available in following definitions:
- select field
- relations
- taxonomies
Image below shows definitions with these settings:
```
required: true
allow_empty: true
```
Manually tested these combinations:
| required | allow_empty |
| - | - |
| none | none |
| none | true |
| none | false |
| true | none |
| true | true |
| true | false |
| false | none |
| false | true |
| false | false |
- automatic validation. Given …
=> New feature: Allow empty value for select form controls, based on user setting.

src/Entity/User.php
This should prepare for the future deprecation of the `Serializable` interface.
=> Update serializable interface

templates/content/_relationships.html.twig
it looks like searchable not used in assets/js/app/editor/Components/Select.vue   only  **:searchable="autocomplete || taggable"**
=> Bugfix Fix autocomplete for Relation 

config/bolt/config.yaml, src/Configuration/Parser/GeneralParser.php, src/Controller/Backend/UserController.php, src/Repository/UserRepository.php, templates/users/listing.html.twig
By default, this feature is disabled, but can be activated by adding user_show_sort&filter: true in bolt/config.yaml
=> Add the possibility to sort and filter users in the backend

src/Event/Subscriber/AuthSubscriber.php
Prevent error on logout when user is not logged in
=> Update AuthSubscriber.php to prevent logout error

docker-compose.yml
Hello!
The current node image used for compiling assets is run using it's default user, which is `root`. However, the image is providing an existing non-root user which is `node`. This one should be used, as mentioned in the [docker node best practices](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user).
When starting the project, assets under the `/public/assets` folder are generated using the `node` image as `root` user, so the files and subfolders are created with `root:root` ownership.
This causes a following Webpack subtask to fail : 
As Bolt is not running a custom image for this service, but is using docker-compose, the easiest tweak would be to just switch the user for the `node` service to the `node` user. Generated file would then inherit the …
=> Avoid running node service as root user

src/Menu/BackendMenu.php
When an admin logs out and right after that a editor logs in the editor sees the cached backendmenu of the admin. This will prevent that.
=> Add a username to the backendmenu cache key

config/bolt/permissions.yaml, src/Security/GlobalVoter.php
This is a suggested 'fix' for issue https://github.com/bolt/core/issues/3079 
This needs to be discussed a bit before merging it in I'd say, especially if this could be the right fix for the wrong problem. 
Should global permissions used in the admin be mixed with permissions used for the front end? If the answer is 'yes' than I'd say this change should probably go in, if the answer is 'no' there should be another solution I'd say.
The global permissions I'm referring to are of course the API ones: 
```
api:get: [ ROLE_WEBSERVICE ] # allow read access to Bolt's RESTful and GraphQL API
api:post: [ ROLE_WEBSERVICE ] # allow write access to Bolt's RESTful and GraphQL API
api:delete: [ ROLE_WEBSERVICE ] # allow delete access to Bolt's RESTful and GraphQL API
```
Reading the docs here …
=> Make it possible for GlobalVoter.php to vote on non-bolt users.

assets/js/app/editor/Components/Date.vue, tests/cypress/integration/edit_record_1_field.spec.js
Added seconds to dateFormat to fix issue with date-compare between database original and edited version, causing users that didn't have the right to change publication dates to be denied making edits.
This fixes https://github.com/bolt/core/issues/3082
Note, this is only for the `dateFormat`, this is used 'behind the scenes' in this vue component and is used to post to the server, the actual format shown is specified in `altFormat`.
=> Update Date.vue dateFormat to include seconds

public/.htaccess
Web inspectors return a 403 error because css source maps were not allowed access
Add map filetype solves this.
=> Add map to htaccess

src/Entity/Field.php, src/Twig/FieldExtension.php
Fix issue #3106 where select field with content type as options can't have an empty value.
=> Fix #3106 : Select field with empty value

assets/js/app/editor/Components/Number.vue, templates/_partials/fields/number.html.twig
This way the amount of decimals after the comma isn't fixed by default
=> Update float field so it uses step='any' by default

src/Canonical.php, src/Event/Subscriber/CanonicalSubscriber.php, src/Menu/FrontendMenu.php
Storing current request in constructor isn't a good idea.
In general, it works (eg: when request from browser or most tests).
But not always.
EG: when test extends WebTestCase and login is executed through `$this->loginUser()`, then container is built without an active request.
Thus, request is null in constructors ...
Proper fix implies storing `$requestStack` and accessing current request when required.
This PR fixes Canonical and FrontendMenu (these failed in my use-case, so far).
=> Use requestStack to access current request when needed.

src/Doctrine/Version.php
this fix is needed when runing tests using dama/doctrine-test-bundle db-rollback support.
This should fix https://github.com/bolt/core/issues/3138
=> handle 'double wrapped' database connections

src/Doctrine/TablePrefix.php, src/Doctrine/TablePrefixTrait.php, src/Doctrine/Version.php
Update TablePrefix.php
Update TablePrefixTrait.php
Update Vresion.php
=> Multiple EntityManagers prefixes

templates/_partials/fields/number.html.twig
since v5.1.5, commit #3122  when number field "mode" is "float" (which is by default), the step is "'any'" by default (note the single quote wrapped by the double quote).  
This "'any'" value should not be escaped because it breaks when the number field is used within a collection. 
For instance, bellow is an extract of an "editor-collection" component generated by the backend when using a collection field having "number" field as child,
we can see it use a :template prop filled with escaped templates of fields members : 
```
<editor-collection
:existing-fields='[]'
:templates='[{ ..  &lt;editor-number  ...  value=\&quot;\&quot;\n    :step=\&quot;&amp;#039;any&amp;#039;\&quot;\n    ...'
:labels='...'
:limit='200'
:name="&quot;gallery_slider_images&quot;"
:variant="&quot;collapsed&quot;" …
```
=> fix number field template so it works within a collection field.

composer.json
We're going to shutdown the flex-server very soon and this locked version will stop working.
It could be great to unlock this constraint on the 4.2 branch, which is the only one affected.
Unless you think this version is too old and it's considered out of maintenance?
=> Bump flex to ^1.17, v1.13 is going to stop working very soon

config/bolt/contenttypes.yaml, src/Entity/Field/ImageField.php
A full explanation/justification for this PR is on #3178
=> #3178 Allow a "thumbnails" property to be configured against a content type field

assets/js/app/editor/Components/Number.vue, config/bolt/contenttypes.yaml, templates/_partials/fields/number.html.twig
Fixes #3184
Default values are now between 0 and 1000.
Probably make a doc where this is noted.
=> Update Number field to include the min and max

src/Doctrine/JsonHelper.php
Tested on MySQL 5.7 and 8.0.26, the bolt admin panel search widget on content was only returning case sensitive results.  When the original code was run on MariaDB, the results were case insensitive.  This fix makes MySQL return case insensitive results.  The issue is described in this StackOverflow answers:
- https://stackoverflow.com/a/59000485
- https://stackoverflow.com/a/63519138/4638563
By casting the JSON_EXTRACT to CHAR, it makes the search case insensitive. 
NOTE: Since this is database specific, I am unable to write a test for the issue.
=> Fix: MySQL was returning case sensitive results.

bin/composer-script/Script.php
To avoid error on installing:
[TypeError]                                                                                                                                                                                             
Symfony\Component\Process\Process::__construct(): Argument #1 ($command) must be of type array, string given, called in bolt/web/vendor/bolt/core/bin/composer-script  
/Script.php on line 57  
We need to fix compare version constraint. 
Composer self-update command updates composer to v2.3-dev+xxxx that is lower than current constraint.
=> Fix version compare for composer self-update versions.

src/Controller/Backend/ContentEditController.php
Bug observed when previewing a record with collection field.
Only last item in collection was available.
`$newFields` variable must be initialized outside the loop in order to capture all collection fields.
=> Fix setting new fields on collection.

src/Event/Subscriber/TimedPublishSubscriber.php
Using a double quote(") character for string literals is not ANSI compatible and should only be used for quoting identifiers.
---
Issue can be reproduced by running bolt on a PostgreSQL backend. The PostgreSQL logs will mention the following:
``` log
2022-05-06 11:37:20.048 UTC [31716] <user>@<database> ERROR:  column "timed" does not exist at character 81
2022-05-06 11:37:20.048 UTC [31716] <user>@<database> STATEMENT:  update bolt_content SET status = "published", published_at = $1  WHERE status = "timed" AND published_at < $2
```
[PostgreSQL docs](https://www.postgresql.org/docs/9.3/sql-syntax-lexical.html):
> A string constant in SQL is an arbitrary sequence of characters bounded by single quotes ('), for example 'This is a string'. 
> There is a second kind of identifier: the …
=> Use single quotes for query string literals

src/Controller/Backend/ContentEditController.php
After finishing computation, restore fields order.
Observed during record preview.
=> Maintain field order.

src/Entity/Content.php, src/Entity/ContentExtrasTrait.php, src/Twig/ContentExtension.php
to avoid name conflicts with fields named icon.
With the current naming it's impossible to name a field `icon` and access it in twig.
=> Renamed the Icon method in the Content class

assets/js/app/editor/Components/Select.vue, assets/scss/vendor/multiselect.scss, config/bolt/contenttypes.yaml, src/Cache/RelatedOptionsUtilityCacher.php, src/Twig/FieldExtension.php, src/Twig/RelatedExtension.php, src/Utils/RelatedOptionsUtility.php, templates/content/_relationships.html.twig
This PR implements the new feature mentioned on issue #3189.
The following features still need to be implemented to have a more complete support of this new feature:
=> Add edit link icon to related content in select/multiselect lists

src/Twig/FrontendMenuExtension.php
which did return false on matching routes with parameters:
This returned `false`, because we compare the full strings:
```
public function isCurrent($item): bool
{
$uri = $item['uri'] ?? '';
return $uri === $this->requestStack->getCurrentRequest()->getPathInfo();
}
```
=> Improved the twig filter "current"

assets/scss/modules/admin/_toolbar.scss
This PR fixes #3234 .
**Before fix:**
**After fix:**
=> Fix avatar image sizes when image is not found

src/Extension/ConfigTrait.php
This PR fixes #3158. 
`array_merge($config, $yamlParser->parseFile($filename));` could return `null` when the config file of an extension was empty or config options are commented out. Now it will default to an empty array to avoid breaking the `/bolt/extensions` extensions listing page
=> Fix error thrown by extensions with no config options defined

src/Utils/FilesIndex.php
=> Get correct relative file path, when `files/` is a symlink

src/Configuration/Content/FieldType.php
=> Additional fix for `type: number` field, set default to `min: 0`.

src/DataFixtures/ContentFixtures.php
Fixes #2946 
When the SEO extension is installed the Fixtures generate a non valid value for the the SEO field. This PR makes sure that the value assigned to a SEO field is valid and prevents the backend from breaking when rendering a non valid value for the SEO field.
=> Add Fixtures for SEO field

src/Twig/ContentExtension.php
👋 Hey!
Fixes #3202
- In the `ImageListField` itself, it will now look for any filled image, not just the first one
- For all `ListFieldInterface` fields, inc. `ImageListField`, `CollectionField` and `SetField`, it'll look through the entire field with nesting to find the first image that qualifies
=> `|image` looks in all possible fields

assets/js/app/common.js
Fixes #3261
I have replace the target `data-bs-toggle="pill"` by `data-bs-toggle="tab"` to fix that issue. It seems in our source code we are not using any HTML element with an attribute like `data-bs-toggle="pill"`. 
It should be safe to replace
=> Enable the hash functionality for tabs instead of pills

src/Utils/Sanitiser.php
Fixes #2898 
Since HTMLPurifier does not support SVG Elements out of the box, this PR adds the SVG Element to the definition, preventing the backend from breaking
=> Add non-supported SVG HTML element to HTML Sanitiser

assets/js/app/common.js
Fixes #3266 
Using `event.currentTarget` instead of `event.target` we can target the button element to get the `data-attribute` values needed to populate the content of the modal even if the user click on the icon or text of the button.
Using event delegation like `window.$(document).on('click', '[data-bs-toggle="modal"]', function(event)` is what we need to make sure new added collection item remove buttons trigger the load of the modal text.
=> Fix loading of modal text when removing collection item

templates/_partials/fields/_base.html.twig, templates/_partials/fields/checkbox.html.twig, templates/_partials/fields/select.html.twig
to be able to include it without the value being overwritten by the base template.
Better explanation:
I'm creating my own field template, which includes checkboxes.
I include the checkbox like this:
```
{% include '@bolt/_partials/fields/checkbox.html.twig' with {
name:  'autoplay-' ~ id,
label: 'autoplay'|trans,
value: autoplay,
} %}
```
The value I pass is either `true` or `false`, obviously.
If I pass `false` the value is somehow overwritten, I'm guessing because they both extend the same base template and both use variables named `value`. 
This now opens the option to pass `false` as a string, which stops twig from using the base template `value`.
Edit on the second commit:
I've also added the option to not print the postfix.
If I include the checkbox template I need this option to …
=> Made the checkbox template recognise a false string as a value

assets/scss/vendor/bootstrap/bootstrap.scss, assets/scss/vendor/flagkit.scss, package-lock.json, package.json, templates/_partials/favicon.html.twig, tests/php/Controller/Backend/ContentEditControllerTest.bak, webpack.config.js
Fixes the build error in latest Bootstrap update: 
```bash
Compiled with some errors in 33.25s
ERROR  Failed to compile with 2 errors                                                                                  13:21:28
error  in ./assets/scss/bolt.scss                                                                                       13:21:28
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
╷
20 │   @each $color, $value in $theme-colors-rgb {
│                           ^^^^^^^^^^^^^^^^^
╵
node_modules/bootstrap/scss/_root.scss 20:27     @import
assets/scss/vendor/bootstrap/bootstrap.scss 5:9  @import
assets/scss/vendor/vendor.scss 4:9               @import
assets/scss/bolt.scss 3:9                        root stylesheet
```
Fixes …
=> Fix some NPM bitrot

src/Controller/Backend/DashboardController.php
Thanks to Eitan at [WhiteSource](whitesourcesoftware.com) for responsibly disclosing this issue to us. 🙏
=> Prevent injection when filtering records

package-lock.json, webpack.config.js
Fixes #3289 
Turns out versioning breaks clearing the cache. (I assume a race condition). Let's disable it for now.
=> No versioning in webpack

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Image.vue, src/Cache/FilesIndexCacher.php, src/Controller/Backend/Async/FileListingController.php, src/Utils/FilesIndex.php, translations/messages.nl.xlf
This PR fixes #3288.
This PR uses the base backend URL set in `bolt.backend_url` in `services.yaml` to populate the image/files modals and it adds a missing Dutch translation for `collection.confirm_delete`
=> Allow image/files modals to be populated from dynamic backend URLs

assets/js/app/editor/Components/Image.vue, assets/js/app/editor/Components/Imagelist.vue, config/bolt/contenttypes.yaml, src/Configuration/Content/FieldType.php, src/Entity/Field/ImageField.php, templates/_partials/fields/image.html.twig, templates/_partials/fields/imagelist.html.twig, tests/php/Configuration/Parser/ContentTypesParserTest.php
For both `image`s and `imagelist`s, you can now add an extra property `extra`:
```
extra:
title:
label: Titel
placeholder: Placeholder
caption:
label: Caption
teaser:
label: Teaser
placeholder: De teaser in het Nederlands
teaser_en:
label: Teaser (EN)
placeholder: De teaser in het Engels
```
For now I have enabled `label` and `placeholder`, but since it's an key,value-array we can expand it if needed. (I initially had it as: `attrib: [ foo, bar, baz ]` to mimick Bolt 3).
---
This seems to work for me. Somehow the solution looks way simpler than I thought. So please double-check if I haven't missed anything.
=> Add extra fields option for `image` and `imagelist` fields

config/bolt/config.yaml, src/Configuration/Parser/GeneralParser.php, src/Event/Subscriber/ProcessWidgetsQueueSubscriber.php, src/Event/Subscriber/WidgetSubscriber.php
Fix issue #1975 where meta snippets are inserted multiple times, via sub-requests for example.
I added an option in config to give the ability to deactivate default canonical insertion.
=> Insert meta snippets on main request only

src/Entity/User.php
To improve import functionality of the Conimex extension this function is necessary to allow the importer to set the ID of the user to whatever the id is in the exported users file. See https://github.com/bobdenotter/conimex/pull/62
=> Add setId() function in User Entity

templates/_base/layout.html.twig, templates/_base/layout_blank.html.twig
Hello,
Just noticed that the title in `layout*.html.twig` files is a little bit too much escaped.
There's a `|striptags` filter which is indeed useful because subsequent title blocks may have html elements in it. But the function does too much escaping.
For example, the title of the login page in french is "S'identifier" which is then displayed as : 
As the content is already stripped from tags, we can just display a `raw` value.
=> Characters escaped when displaying the title bloc in templates

src/Controller/Backend/ContentEditController.php, src/Repository/RelationRepository.php
_This scratches my personal itch, where I want to nudge my Bolt-powered blog slightly more towards a knowledge-base thingy, where I can keep track of posts linking to other posts. To do this properly, I want to distinguish between incoming and outgoing links for a post._
Currently, a Content can have Relations To and From itself. In the edit interface, they're all thrown onto one pile, and when saving such an entry, all the relations will be, from that point on, From that content (even if they were in fact To it, before). This change fixes that, by more carefully storing and removing Relations. 
- Only remove existing Relations if they are actually no longer used
- Only add new Relations if they weren't already present
- Keep and fetch Relations in the correct order, default to sorting by …
=> Keep relation direction when updating content.

src/Widget/Injector/RequestZone.php
Crashed today in one of my production environments:
Unfortunately I couldn't use the null-safe operator here :(
=> Check for empty request before using it

bin/fix-bundles.php
This prevents the confusing messsages like this from showing up: 
```
sh: 1: exec: vendor/bolt/core/bin/fix-bundles: not found
Processed 0 files. Updated: 0, deleted: 0, skipped: 0.
```
=> Since we call it using `self::runPHP`, we don't need the shebang

src/Event/Listener/ContentFillListener.php
As seen with @bobdenotter, author can be `null` sometimes, especially on ContentType creation from forms with `bolt/forms`.
=> Make guesstimateAuthor return type nullable

src/Utils/Excerpt.php
but would be long enough _before_ trimming in order to skip returning the `fulltext` instead.
The issue lies in a piece of small text that would be longer than the excerpt length `relLength`, but when trimmed at https://github.com/bolt/core/blob/master/src/Utils/Excerpt.php#L110-L112 would overflow resulting in a negative starting position. This gives an undesired result (and potenttially no highlight).
=> Fix `excerpt` when content would be too short _after_ trimming

src/Twig/FrontendMenuExtension.php
before comparing, to the current route to get continuous results across all languages.
/en/products becomes /products, which we then compare to the path info.
=> Made the is current filter remove the current locale 

assets/js/app/editor/Components/Select.vue, templates/_partials/fields/select.html.twig
This eventually caused Relations selects for new content to have the first Related option pre-selected. Not entirely sure where this change came from and what the thought behind it was, so I cannot in full confidence say that this one won't break anything. I'd like @bobdenotter and @I-Valchev (and possibly @nestordedios ?) to weigh in.
Fixes #3370
=> Don't blindly pre-select the first option in a filter.

src/Entity/Content.php
Fix issue #3389 where SetField is converted into an array in twig instead of keeping the object, resulting on some BC breaks.
=> Fix #3389 : Do not display twig value for SetField

config/bolt/config.yaml, src/Configuration/Parser/GeneralParser.php, src/Controller/ImageController.php, src/Twig/ImageExtension.php, src/Utils/ThumbnailHelper.php
The thumbnail quality setting works now. I have also added a `$quality` parameter as the last parameter of the `thumbnail` filter. I have also brought the quality setting in `GeneralParser`'s default config in line with the default in `config.yaml`. As a result of my changes, quality is now the 3rd element of generated thumbnail paths. 
I have removed superfluous settings from `config.yaml` (`cropping` and `allow_upscale` – both seem to be superseded by the `$fit` parameter of the `thumbnail` filter).
I have tried to make my changes as undisruptive as possible, but I still recommend giving them a good look over.
=> 3115-thumbnails-parameters

templates/helpers/_languageselect.html.twig
According to the documentation https://docs.boltcms.io/5.0/twig-components/languageselect the language switcher should be usable without type: 
```twig
{% include 'helpers/_languageselect.html.twig' %}
```
However, not setting the type like below will throw an error:
```stacktrace
Twig\Error\RuntimeError:
Variable "type" does not exist.
at vendor/bolt/core/templates/helpers/_languageselect.html.twig:22
at __TwigTemplate_2281140af09e6102e86e7eafa527bafd11b91df66b58316afb745dd4e298e615->{closure}()
(var/cache/dev/twig/58/58f807167b332d30faaf3f3777118f147f078e150977e0ac1d19f218da238901.php:57)
at __TwigTemplate_2281140af09e6102e86e7eafa527bafd11b91df66b58316afb745dd4e298e615->doDisplay()
(vendor/twig/twig/src/Template.php:394)
at Twig\Template->displayWithErrorHandling() …
```
=> Fix language switcher failing to set a default "type" value

src/Entity/Field/CollectionField.php, src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php, src/Entity/Field/SelectField.php, src/Entity/Field/SetField.php, src/Security/AuthenticationEntryPointRedirector.php
Pinging @enrise-mbraam , I had to partially revert your recent PR, because the removal of `Iterator` causes things like this to stop functioning: 
```
{% for image in record.gallery %}
{{ image|popup() }}
{% endfor %}
```
Could you take another look at what was breaking on your end, and if we can do an alternative fix for that? :-)
=> Partial reverse of #3395, we really need those `\Iterator`s

src/Entity/Field.php
allow_twig : prevent saving error (translations getting cleared if Twig code contains errors)
When inserting twig code (for example in an Article field), if the code contains one or more error, the content is saved in the current locale... but others translations are cleared.
=> allow_twig : prevent saving error

bin/composer-script/Script.php
commands executed from the post-update-cmd are not executed on windows. unshifting the executable as parameter seems to the fix the problem.
=> try to fix failing composer script on windows

src/Security/LoginFormAuthenticator.php
This makes the "remember me" checkbox actually work by setting the relevant cookie on login.
=> Fix: Add RememberMeBadge to the login form authenticator.

src/Utils/LocaleHelper.php
This prevents us from attempting to create a route without a slugOrId, which would only make the Router sad.
Fixes #3442
=> Only attempt to get a link to content with a slug for the locale.

translations/messages.en.xlf
The unit tag with the name "9fb3e6e" completely repeats in meaning and content the unit tag with the name "general.purpose.built-with-bolt". I'm talking about the messages.en.xlf file. I suggest deleting this unit tag with the name "9fb3e6e".
=> Delete duplicated unit in messages.en.xlf

assets/js/app/editor/Components/Select.vue, src/Controller/Backend/Async/SelectOptionsController.php, src/Twig/FieldExtension.php, templates/_partials/fields/_base.html.twig, templates/_partials/fields/select.html.twig
Allows the use of `lazy: true` for contenttype-queries on select fields. __Potentially__ useful on sites that have a lot of records that need to be processed before rendering the template/response. This is a proof-of-concept for now. I've chosen an opt-in method since this will be very niche, and we will have to see whether we get the gains, or not.
```diff
selected_pages:
type: select
label: "Select Pages"
values: "pages/{contenttype} Nº{id}: {title} - {status}"
autocomplete: true
multiple: true
limit: 1000
variant: inline
+   lazy: true
```
When components get initialized (mounted), they will each query the server for the list of options. This is to ensure that the selected values are properly selected and shown in the UI. The problem stems that they will do so simultaneously. After …
=> Allow `lazy` as an option for select fields using contenttype-queries

assets/js/app/common.js
The fix is for the issue https://github.com/bolt/core/issues/3488
The solution is to check only input in #editor, otherwise the global search field is find first
=> fix(editor): check only editor input:invalid

assets/scss/init/_variables.scss, assets/scss/vendor/bootstrap/bootstrap.scss, package-lock.json, package.json
This PR adds the following changes: 
- Updates Bootstrap to v5.3.2 which fixes compilation warnings as stated in their tag release https://github.com/twbs/bootstrap/releases/tag/v5.3.2
- Adds some new variables with Bootstrap default values (This is necessary to prevent Node Sass to compile using CSS variables, which is impossible and breaks the compilation)
- Remove unused variables
=> Remove abs() deprecation warnings when compiling assets

src/Controller/ImageController.php
Solves a `Warning: Undefined array key 1` notice.
Some clients do not understand how to use UTF-8, and execute a request to for example `/thumbs/400%C3%83%C2%97400%C3%83%C2%97contain/news`, which contains `Ã` instead of the expected `×`. I do not know why `%83%C2` is inserted in the URL (it is some sort of Python based external scanner...), but I do believe this code should be robust enough to not throw a warning when this happens. With this change the raw parameters are checked for existence before being used, allowing for a sane fallback.
I do not believe the CI failures are related to this change.
=> Handle incorrect parameters gracefully

templates/_partials/fields/select.html.twig, templates/content/_relationships.html.twig
This PR adds a fix for a bug introduced on PR #3477(Allow setting a limit for the options displayed in relationships selects)
The limit option is now set to the general config option `maximum_listing_select` or 2000 by default.
If a relation or select field has the `limit` option defined, the limit will be set to the value of that option.
=> Set limit per relation and select field option

compose.yml
This PR upgrade the Docker compose configuration and remote the Blackfire rependency.
Blackfire's free plan is no longer available
=> :construction_worker: update the Docker compose configuration

.github/workflows/a11y_tests.yaml, .github/workflows/api_tests.yaml, .github/workflows/code_analysis.yaml, .github/workflows/cypress_tests.yaml, .github/workflows/unit_tests.yaml
This PR updates the GitHub Action workflows to use the latest versions of the actions and their specific configuration.
`shivammathur/setup-php@v2` installs the latest version of composer which removes the update actions.
It also installs the Symfony client which can be used as a web server for testing.
This removes the `symfony/web-server-bundle` dependency.
=> :white_check_mark: Update Github action workflow

.github/workflows/api_tests.yaml, composer.json, src/Api/Extensions/ContentExtension.php, src/Doctrine/Functions/Rand.php, src/Doctrine/Query/Cast.php, src/Entity/Field.php, symfony.lock, templates/pages/about.html.twig
The development dependency `coduo/php-matcher` is not used in code and lock the `doctrine/orm` update.
See issue #3551
=> :arrow_up: remove unused coduo/php-matcher dependency - issue #3551

composer.json, src/Controller/Backend/Async/EmbedController.php
See #3551 
Embed field tested :heavy_check_mark: 
Url tested `https://www.youtube.com/watch?v=nKGdPVohVv8`
Response:
```json
{
"title": "Win32Service en action",
"author_name": "JB Dev Labs",
"author_url": "https:\/\/www.youtube.com\/@jbdevlabs",
"type": "video",
"height": 113,
"width": 200,
"version": "1.0",
"provider_name": "YouTube",
"provider_url": "https:\/\/www.youtube.com\/",
"thumbnail_height": 360,
"thumbnail_width": 480,
"thumbnail_url": "https:\/\/i.ytimg.com\/vi\/nKGdPVohVv8\/hqdefault.jpg",
"html": "\u003Ciframe width=\u0022200\u0022 height=\u0022113\u0022 src=\u0022https:\/\/www.youtube.com\/embed\/nKGdPVohVv8?feature=oembed\u0022 frameborder=\u00220\u0022 allow=\u0022accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\u0022 …
```
=> :arrow_up: Update dependency embed/embed
