package.json, yarn.lock
As discussed in #10, It add basic eslint and prettier integration by following [this guide](https://alligator.io/vuejs/vue-eslint-prettier/).
=> [fixes #10] Add initial eslint & prettier integration

src/Entity/Content.php
=> Only allow GET operations in the API

src/Twig/Extension/ContentHelperExtension.php, templates/editcontent/edit.twig
Fixes #44 
@jackiboy Feel free to merge in, after review! :-)
Screenshot: 
```twig
{{ icon(record) }} Edit {{ record.definition.singular_name }} » <strong>{{ record.title|default('New') }}</strong>
```
=> Add icon and contenttype to Title {% block %}

config/bolt/config.yaml
=> Add `resolve` again (for SQLite)

README.md
These are kinda required if you want to be able to open the backend. ;)
=> Add the bits about NPM install.

src/Content/MenuBuilder.php, src/Form/UserType.php, src/Twig/Extension/ContentHelperExtension.php, templates/_base/layout.twig, translations/messages.en.xlf
Look, @jackiboy : This way we can inject labels into the Vue components.
=> Injecting labels in topbar Vue component

assets/js/Components/Admin/Header.vue, assets/js/Components/Admin/Toolbar.vue, assets/js/Components/Base/Notification.vue, assets/js/Components/Editor/Image.vue, assets/js/Components/Editor/Slug.vue, assets/js/Views/editor.js, assets/js/Views/notifications.js, assets/js/bolt.js, assets/scss/modules/base/_notification.scss, assets/scss/modules/base/base.scss, assets/scss/vendor/bootstrap/bootstrap.scss, assets/scss/vendor/selectize/_variables.scss, assets/scss/vendor/selectize/selectize.scss, package-lock.json, package.json, templates/_base/layout.twig, templates/_partials/_flash_messages.twig, templates/editcontent/edit.twig, translations/messages.en.xlf, translations/messages.es.xlf
Added custom notification snackbar component to replace the bootstrap ones
=> added custom notifications

src/Entity/Content.php, src/Entity/ContentMagicTraits.php, src/Twig/ContentHelperExtension.php, templates/_partials/_content_listing.twig, templates/content/listing.twig
@jackiboy See `{{ jsonrecords(records) }}` in `_content_listing.twig`. 😇
=> Adding `jsonrecords()` twig function.

src/Controller/Backend/UserController.php, templates/editcontent/fields/email.twig, templates/editcontent/fields/password.twig, templates/users/edit.twig
Form fields are not fully customisable yet(needs more work).
=> Replace Symfony Forms by Edit User custom form

.gitignore, .travis.yml, Makefile, composer.json, composer.lock, easy-coding-standard.yml, phpcs.xml.dist, phpstan.neon, src/Configuration/Parser/GeneralParser.php, src/Configuration/PathResolver.php, src/Content/FieldType.php, src/Content/MediaFactory.php, src/Controller/Async/News.php, src/Controller/Backend/ContentOverviewController.php, src/Controller/Frontend/ListingController.php, src/Controller/Frontend/SearchController.php, src/Controller/Frontend/TaxonomyController.php, src/Entity/Content.php, src/Repository/ContentRepository.php, symfony.lock
`make cscheck` should be added to Travis
=> ECS Config

src/Content/MediaFactory.php, src/Controller/Async/News.php, src/Controller/Frontend/HomepageController.php, src/Controller/Frontend/PreviewController.php, src/Entity/Content.php
=> Throw Exception instead of die()-ing.

assets/js/Views/user.js, assets/js/app/editor/Components/Editor/index.js, assets/js/app/editor/index.js
I _think_ it needs to be removed. If not, close this pull request. Partial fix for #169 
Edit: Hmmm... maybe someone needs to add the `_Partials/Label` instead 🤔
=> Remove references to Label component

src/DataFixtures/ContentFixtures.php
=> Making fixtures work again

README.md
=> Update 'linuxy' to 'UNIX-like'

templates/_partials/fields/geolocation.html.twig
=> Base layout for Geolocation field

Makefile, README.md, docker-compose.yml, docker/nginx/default.conf, docker/nginx/default.conf.template, docker/nginx/entrypoint.sh, docker/php/Dockerfile, docker/php/confd/conf.d/php_ini.toml, docker/php/confd/templates/php_init.tmpl, docker/php/entrypoint.sh
So nobody would need to install node, nginx and even php.
See #190
=> add docker env

Makefile, phpstan.neon, public/theme/skeleton/index.twig, src/Configuration/Config.php, src/Configuration/Parser/GeneralParser.php, src/Content/MediaFactory.php, src/Content/MenuBuilder.php, src/Controller/Backend/FileEditController.php, src/Controller/Backend/MediaController.php, src/DataFixtures/ContentFixtures.php, src/Storage/Query/Handler/SelectQueryHandler.php, src/Storage/Query/SelectQuery.php, src/Twig/ArrayExtension.php, src/Twig/HtmlExtension.php, src/Twig/LocaleExtension.php
=> PHPStan level 3

assets/js/app/editor/Components/Editor/Date/Date.vue, assets/js/app/editor/Components/Editor/Date/index.md, assets/js/app/editor/Components/Editor/Html/Html.vue, assets/js/app/editor/Components/Editor/Image/Image.vue, assets/js/app/editor/Components/Editor/Markdown/Markdown.vue, assets/js/app/editor/Components/Editor/Number/Number.vue, assets/js/app/editor/Components/Editor/Select/Select.vue, assets/js/app/editor/Components/Editor/Slug/Slug.vue, assets/js/app/editor/Components/Editor/Text/Text.vue, assets/js/app/editor/Components/Editor/Textarea/Textarea.vue, assets/js/app/editor/Components/Editor/index.js, assets/js/app/editor/Components/General/Language/Language.vue, assets/js/app/editor/Components/General/index.js, package.json
`prettier --single-quote  --trailing-comma --write assets/js/app/editor/Components/**/*`
=> Some minor JS cleanup (with Prettier)

.travis.yml
=> Fix Travis for PHP 7.1

config/packages/security.yaml
=> Hotfix: don't add `/bolt` to security.yaml yet. See #245

config/services.yaml, src/Configuration/Config.php, src/Configuration/Parser/BaseParser.php
Gives ~10% or ~6ms performance gain on simple pages. 
Before: 
After: 
Fixes #263
=> Cache config files

tests/php/DbAwareTestCase.php, tests/php/Twig/AbstractTestTokenParser.php, tests/php/Twig/SetcontentTokenParserTest.php, tests/php/Twig/TokenParserTestCase.php
Not a lot, but better than none. ;-)
Fixes #289
=> [tests] Port `{% setcontent %}` tokenparser tests

src/Content/MenuBuilder.php
=> Fix Admin menu links

assets/js/app/editor/Components/Editor/Select/Select.vue, templates/_partials/fields/_base.html.twig, templates/_partials/fields/select.html.twig, templates/content/_fields_aside.html.twig, templates/content/_taxonomies.html.twig
=> Add `allowempty` flag to prevent save record with empty status

templates/_partials/fields/_base.html.twig, templates/_partials/fields/file.html.twig, templates/_partials/fields/generic.html.twig, templates/content/_fields.html.twig, templates/pages/about.html.twig, templates/pages/placeholder.html.twig, tests/e2e/features/edit_record.feature, tests/e2e/features/kitchensink.feature, tests/e2e/pages/kitchensink.js
=> Kitchensink / Fields improvements

config/packages/stof_doctrine_extensions.yaml, config/services.yaml, src/Content/MenuBuilder.php, src/Controller/Backend/ContentEditController.php, src/Controller/BaseController.php, src/Entity/Content.php, src/Entity/ContentMagicTrait.php, src/Entity/Field.php, src/Entity/Translatable.php, src/EventListener/ContentFillListener.php, src/EventListener/PreTranslatableListener.php, src/EventSubscriber/LocaleSubscriber.php, src/Twig/LocaleExtension.php, src/Twig/TranslatableExtension.php, templates/content/view_locales.html.twig, tests/e2e/features/edit_record.feature, tests/e2e/package.json, tests/e2e/pages/edit_record.js, translations/messages.en.xlf, translations/messages.nl.xlf
=> Fix field values not being translated while editing content in different language

.env.dist, docker-compose.yml, docker/php/Dockerfile
=> Enable Blackfire performance testing on Docker

src/Controller/Backend/AuthenticationController.php, src/Controller/Backend/ContentEditController.php, src/Controller/Backend/ContentOverviewController.php, src/Controller/Backend/DashboardController.php, src/Controller/Backend/DatabaseIntegrityController.php, src/Controller/Backend/EditMediaController.php, src/Controller/Backend/FileEditController.php, src/Controller/Backend/FixturesController.php, src/Controller/Backend/GeneralController.php, src/Controller/Backend/MediaController.php, src/Controller/Backend/OmnisearchController.php, src/Controller/Backend/ProfileController.php, src/Controller/Backend/UserController.php, templates/_base/layout.html.twig, templates/_partials/fields/_base.html.twig, templates/content/_fields.html.twig, templates/pages/placeholder.html.twig
This is required to use `bolt/four` as a composer dependency, so it's part of #166
=> Consistently use the '@bolt' namespace in templates

templates/pages/about.html.twig
- add Blackfire
- set target blank on all links
=> Update "About" page

public/theme/skeleton/partials/_header.twig, public/theme/skeleton/partials/_master.twig, public/theme/skeleton/record.twig, public/theme/skeleton/search.twig, src/Configuration/Config.php, tests/e2e/features/display_record.feature, tests/e2e/features/edit_record.feature, tests/e2e/pages/single_record.js
Fixes #343 
This PR can serve as a workaround, allowing us to carefully make an elegant solution in #344
=> Use `.hasField('…')` to check for existence of fields

public/theme/skeleton/record.twig, src/Entity/Content.php
=> Be more lenient when calling non-existant object properties from within Twig

src/DataFixtures/ContentFixtures.php, tests/e2e/features/display_listing.feature, tests/e2e/features/edit_record_1.feature
=> [Hotfix] Solidify e2e tests, make sure required entry is published

config/bolt/config.yaml, config/bolt/contenttypes.yaml
Fixes #361 
Some are left that currently don't do anything, but it's the _intent_ to make them work and/or re-introduce the required functionality.
=> Cleanup of config files

public/theme/skeleton/partials/_sub_taxonomylinks.twig, src/Controller/Backend/ContentOverviewController.php, src/Controller/Frontend/ListingController.php, src/Controller/Frontend/SearchController.php, src/Controller/Frontend/TaxonomyController.php, src/DataFixtures/BaseFixture.php, src/DataFixtures/ContentFixtures.php, src/DataFixtures/TaxonomyFixtures.php, src/DataFixtures/UserFixtures.php, src/Entity/Taxonomy.php, src/Repository/ContentRepository.php, src/Twig/ContentExtension.php, tests/e2e/features/display_taxonomies.feature, tests/e2e/pages/listing_taxonomies.js, tests/e2e/pages/single_record.js
=> Displaying Taxonomies in frontend

src/Twig/LocaleExtension.php, src/Twig/RecordExtension.php, src/Twig/WidgetExtension.php
Fixes #364 
Needs a rebase on master first, after #372 is merged in.
=> Refactor uses of `$env` to `$twig`

Makefile, public/theme/skeleton/index.twig, public/theme/skeleton/listing.twig, public/theme/skeleton/partials/_master.twig, templates/_base/layout.html.twig, tests/spec/Bolt/Menu/BackendMenuBuilderSpec.php
=> Use default filter instead of is defined in Twig

src/Widget/Injector/HtmlInjector.php, tests/php/Widget/WidgetsTest.php
=> [hotfix] Only invoke widget, when we intend to inject it.

assets/js/app/listing/Components/Table/Row/_Actions.vue, src/Controller/Backend/ContentEditController.php, src/Entity/Content.php, src/Twig/ContentExtension.php, templates/content/edit.html.twig, tests/spec/Bolt/Twig/ContentExtensionSpec.php, translations/messages.en.xlf
Fixes #424. Fixes #425. Fixes #426.
=> Add Controllers for 'duplicate', 'change status' and 'delete'

composer.json, config/bolt/contenttypes.yaml, src/Controller/Backend/ContentEditController.php, src/Twig/RelatedExtension.php, templates/content/_relationships.html.twig, templates/content/_taxonomies.html.twig, templates/content/edit.html.twig, tests/spec/Bolt/Twig/RelatedExtensionSpec.php
Fixes #330. Fixes #329. 
Replaces / closes #418.
=> Editing relations, attempt 2

src/Configuration/Content/ContentType.php, src/Entity/ContentLocalizeTrait.php, src/Twig/ContentExtension.php
We need to be more user-friendly
=> [hotfix] Be more tolerant when contenttype is deleted from config

config/bolt/config.yaml, config/bolt/contenttypes.yaml, src/Configuration/Config.php, src/Controller/Backend/ContentOverviewController.php, src/Controller/Backend/DashboardController.php, tests/e2e/features/dashboard.feature, tests/php/Configuration/Parser/ContentTypesParserTest.php
=> Fix "records_per_page" configuration setting

src/Storage/Query/SelectQuery.php, templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig
=> Use 'andWhere' instead of 'where'

config/bolt/contenttypes.yaml, public/theme/skeleton/partials/_sub_field_blocks.twig, public/theme/skeleton/partials/_sub_fields.twig, public/theme/skeleton/test.twig, src/Configuration/Content/FieldType.php, src/Configuration/Parser/ContentTypesParser.php, src/Controller/Frontend/DetailController.php, src/DataFixtures/ContentFixtures.php, src/Entity/Field.php, src/Entity/Field/MarkdownField.php, src/Entity/Field/SelectField.php, src/Twig/HtmlExtension.php, src/Utils/Markdown.php, src/Utils/Sanitiser.php, tests/e2e/features/display_record_test.feature, tests/e2e/pages/single_test.js, tests/php/Configuration/Parser/ContentTypesParserTest.php
=> Add HTML Sanitiser for fields

composer.json, src/Entity/Field.php, src/Entity/Field/BlockField.php, src/Entity/Field/CheckboxField.php, src/Entity/Field/DateField.php, src/Entity/Field/EmbedField.php, src/Entity/Field/FileField.php, src/Entity/Field/FilelistField.php, src/Entity/Field/FloatField.php, src/Entity/Field/GeolocationField.php, src/Entity/Field/HiddenField.php, src/Entity/Field/HtmlField.php, src/Entity/Field/ImageField.php, src/Entity/Field/ImagelistField.php, src/Entity/Field/IntegerField.php, src/Entity/Field/MarkdownField.php, src/Entity/Field/NumberField.php, src/Entity/Field/RepeaterField.php, src/Entity/Field/SelectField.php, src/Entity/Field/SlugField.php, src/Entity/Field/TemplateselectField.php, src/Entity/Field/TextField.php, src/Entity/Field/TextareaField.php, src/Entity/Field/VideoField.php, src/Entity/FieldInterface.php, src/Event/Listener/FieldDiscriminatorListener.php, tests/api/content/get_content_fields.feature
=> Remove 'static' from 'public function getType()'

README.md
Upon installing I did not find all info that clear to get to a running Bolt 4 environment. So I added some stuff and formatted some text to make it a bit more to the point of installing a working environment
=> Some clarification and formatting in the README

assets/scss/init/_base.scss, assets/scss/init/_variables.scss, assets/scss/modules/editor/fields/_date.scss, assets/scss/modules/listing/row/row.scss, package-lock.json
=> Minor changes in CSS, tiny cleanup

assets/scss/init/_variables.scss, assets/scss/modules/base/_buttons.scss, assets/scss/modules/base/base.scss, templates/pages/kitchensink.html.twig, tests/e2e/features/kitchensink.feature
fixes #493 
+ small extra comments on yiq
=> Adds hidden-danger class - #493

assets/scss/modules/editor/fields/_image.scss, templates/finder/_uploader.html.twig
Does the styling part of #463 to a pretty blue block
=> Styling dropzone #463

assets/js/bolt.js, package-lock.json, package.json, templates/finder/_uploader.html.twig
Fixes #463. Second part, first part was #501
=> Use Dropzone locally, not from CDN

.gitignore, tests/e2e/package-lock.json, tests/e2e/package.json
=> Update Kakunin, other deps, make it work again

assets/scss/init/_variables.scss, assets/scss/layout/_admin.scss, templates/_base/layout.html.twig, templates/bundles/TranslationBundle/WebUI/base.html.twig, templates/finder/editfile.html.twig
=> Aside block var check, add class and rewrite grid layout. Removed widecontent class

translations/messages.it.xlf
First release for the italian translation of Bolt messages
=> Italian translation

assets/js/app/sidebar/Components/Sidebar.vue, assets/js/app/sidebar/Components/_SidebarToggler.vue, assets/scss/modules/admin/_sidebar.scss, templates/_base/layout.html.twig
Fixes #496 
Partial work for #474
=> some improvements to sidebar, button and version link

src/Event/Subscriber/ExtensionSubscriber.php, src/Event/Subscriber/WidgetSubscriber.php, src/Extension/BaseExtension.php, src/Extension/ExtensionInterface.php, src/Extension/ExtensionRegistry.php
=> Let Extensions add Twig Filters and Functions and Bolt Widgets

src/Controller/Backend/ContentOverviewController.php, src/Repository/ContentRepository.php, templates/_partials/_pager.html.twig, templates/content/listing.html.twig
=> Make filtering options work

src/Controller/Backend/ProfileController.php, templates/users/edit.html.twig, templates/users/profile.html.twig, translations/messages.en.xlf, translations/security.en.xlf, translations/validators.en.xlf
=> Fix weird logic in "Edit Profile"

assets/scss/modules/editor/fields/_html.scss
=> Fix "full screen" for wysiwyg editor.

composer.json, templates/bundles/TranslationBundle/WebUI/base.html.twig
=> Bump `php-translation/symfony-bundle` to `0.9.0`

src/Command/AddUserCommand.php, templates/_partials/fields/password.html.twig, templates/users/edit.html.twig, translations/messages.en.xlf, translations/messages.nl.xlf
=> Hide new passwords by default, still keeping suggestions

templates/_partials/fields/_base.html.twig, templates/_partials/fields/checkbox.html.twig
=> Minor tweaks to checkbox

.travis.yml, tests/e2e/package-lock.json, tests/e2e/package.json
Currently Kakunin breaks on Travis:
=> Update Kakunin dependencies

templates/content/edit.html.twig
=> When pressing enter, save the record instead of previewing it

assets/scss/vendor/bootstrap/bootstrap.scss, package-lock.json, src/Controller/Backend/MediaEditController.php, src/Entity/Media.php, templates/media/edit.html.twig, translations/messages.en.xlf, translations/messages.nl.xlf
=> Allowing focal point settings for thumbnail images

assets/scss/vendor/codemirror.scss
=> Markdown field gets a bit more padding at the bottom

assets/js/app/sidebar/Components/Menu/_SubMenu.vue
=> Make sidebar menu show `(Untitled)` instead of "blank" for records without title. 

src/Controller/Backend/UserEditController.php, src/Security/LoginFormAuthenticator.php
'', null, and [] all empty. If attempting validation, fail. If admin
trying to edit user, don't update password
=> #625 empty password throws 500

assets/js/app/editor/Components/Password.vue, assets/js/app/editor/Components/ProgressBar.vue, assets/js/zxcvbn.js, package-lock.json, package.json, src/Controller/Backend/UserEditController.php, templates/_partials/fields/password.html.twig, templates/users/edit.html.twig, templates/users/profile.html.twig, webpack.config.js
Modified Password.vue to add optional ProgressBar
Added zxcvbn library to test password strength
Added library to templates that use it
Changed Twig variable away from 'user' (overwrites logged in 'user')
=> Issue 516 add password strength bar

config/bolt/config.yaml, src/Twig/RecordExtension.php, templates/_partials/fields/select.html.twig, translations/messages.en.xlf
=> Making `type: select` fields work with selecting from a ContentType

assets/scss/layout/_admin.scss, assets/scss/modules/admin/_header.scss
=> fix aligment main container and grid gutter on breakpoints

src/DataFixtures/BaseFixture.php, src/DataFixtures/ContentFixtures.php, src/DataFixtures/TaxonomyFixtures.php, src/DataFixtures/UserFixtures.php
=> Only add preset fixtures on first run, not on consecutive ones

src/Twig/LocaleExtension.php, src/Utils/LocaleHelper.php, templates/content/_localeswitcher.html.twig
=> Fix duplicated items in locale switcher

src/Event/Subscriber/ExtensionSubscriber.php, src/Extension/BaseExtension.php
Hi @bobdenotter this is what we have done to be able to get some services from the container when creating extensions. If this is not the way to go in the end just skip the PR.
=> Pass container to Extensions

templates/_base/layout.html.twig
=> Bugfix unknown user maintenance pages

assets/js/app/common.js, assets/js/app/editor/Components/Language.vue
=> have hash on tabs

src/Command/ExtensionsServicesCommand.php, src/Event/Subscriber/ExtensionSubscriber.php, src/Extension/ExtensionRegistry.php
=> Don't run an Extension's `initialize` on CLI

assets/js/app/common.js, composer.json, config/packages/framework.yaml, config/packages/security.yaml, src/Entity/User.php, src/Entity/UserAuthToken.php, src/Repository/UserAuthTokenRepository.php, src/Security/LoginFormAuthenticator.php, src/Security/LogoutListener.php, symfony.lock, templates/users/listing.html.twig, tests/php/Security/LoginFormAuthenticatorTest.php, tests/spec/Bolt/Security/LoginFormAuthenticatorSpec.php, translations/messages.en.xlf
What is the correct way to display dates on the Bolt backend?
[This twig extension](https://twig-extensions.readthedocs.io/en/latest/date.html) allows relative times such as `4 seconds ago` and `in one month`, but I could not install it correctly because it requires the higher `doctrine/dbal` version, on hold because of #702 .
For now this is shown e.g. `2019-11-06 12:35:19`
=> session info shown on view users

assets/js/app/editor/Components/Image.vue, assets/js/app/editor/Components/Imagelist.vue, assets/js/app/editor/Components/Language.vue, assets/js/app/editor/Components/Select.vue, assets/scss/init/_variables.scss, assets/scss/modules/editor/_forms.scss, assets/scss/modules/editor/fields/_image.scss, config/bolt/contenttypes.yaml, package-lock.json, public/theme/skeleton/index.twig, src/Controller/Backend/MediaEditController.php, src/Entity/Field/ImageField.php, templates/_partials/fields/_base.html.twig, templates/_partials/fields/geolocation.html.twig, templates/_partials/fields/image.html.twig, templates/_partials/fields/imagelist.html.twig, templates/content/_relationships.html.twig, templates/content/_taxonomies.html.twig, translations/messages.en.xlf
(Because images are tied to the Image entity for meta-tags, and contextual stuff like 'titles' and 'captions' should be part of a fieldset.)
=> Remove Title attribute from Image field

config/bolt/config.yaml, src/Controller/ExceptionController.php, src/DataFixtures/ContentFixtures.php, src/Event/Subscriber/MaintenanceModeSubscriber.php, templates/helpers/page_503.html.twig
=> Make "Maintenance mode" work.

assets/js/app/editor/Components/Select.vue
=> Remove unneeded attribute

composer.json, symfony.lock
=> Don't mention "Package container-interop/container-interop is abandoned"

public/theme/skeleton/custom/test.twig, src/Configuration/Content/FieldType.php, src/Configuration/Parser/ContentTypesParser.php, tests/php/Configuration/Parser/ContentTypesParserTest.php
=> Improve fieldtype factory creation

src/Utils/LocaleHelper.php
=> De-duplicate Locales array

translations/messages.de.xlf, translations/messages.en.xlf
Added the german translation ( a part of it).
@bobdenotter please generate the missing string, as discussed on slack.
=> Added the german translation

assets/js/app/editor/Components/Image.vue
=> Fixed bug which reveals hidden input while using tab

assets/js/app/editor/Components/Password.vue, assets/scss/modules/user/user.scss, templates/finder/_uploader.html.twig, templates/helpers/_pager_bootstrap.html.twig, translations/messages.de.xlf, translations/messages.en.xlf
This PR will
- use `pointer` as cursor for the toggle password button
- adds translation for the dropzone droptext and for the pager
=> Small fixes

run_behat_tests.sh
=> Bump chromedriver version to 78

assets/js/app/editor/Components/File.vue
Fixes #741 for file fields too
=> Fix hidden field tabindex in File.vue

assets/js/app/editor/index.js
Fixes #788
And git blames me 😳
=> Email field works again

templates/_partials/fields/collection.html.twig
A small tweak to make sure the editor works for a new collection
=> Bugfix for collection with no existing fields

src/Entity/Relation.php
Note: Be sure to run `bin/console doctrine:schema:update --force` after updating.
Fixes #784
=> Add `onDelete="CASCADE"` for Relations, to delete them properly.

templates/users/edit.html.twig
=> Show all locales in user selection

assets/js/vibrant.js, package-lock.json, package.json, templates/media/edit.html.twig, webpack.config.js
This pullrequest removes the cdn of vibrant and adds a new javascript file for it.
=> removed vibrant as cdn and added it using packagemanger

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Image.vue, assets/js/app/editor/Components/Imagelist.vue, templates/_partials/fields/_base.html.twig, templates/_partials/fields/filelist.html.twig, templates/_partials/fields/imagelist.html.twig, tests/behat/edit_record_1.feature, translations/messages.en.xlf
=> Tweaking filelist and imagelist

src/Entity/Field/TemplateselectField.php
=> Fix Templateselect showing up as JSON

src/Twig/DumpExtension.php, src/Twig/TokenParser/DumpTokenParser.php, src/Twig/TokenParser/SetcontentTokenParser.php
=> Suppress {{ dump }} and {% dump %} when in PROD mode

templates/_macro/_macro.html.twig, templates/users/listing.html.twig, tests/behat/users.feature, translations/messages.en.xlf, translations/messages.nl.xlf
=> Cleaning up User listing page

config/services.yaml, src/Configuration/Parser/ContentTypesParser.php, src/Twig/DumpExtension.php
=> Make sure we don't sort on non-existing field or timestamp

src/Configuration/Parser/ContentTypesParser.php
=> Ensure default status is a valid one

templates/helpers/_fields.twig
=> [chore] cleanup `_fields.twig`

templates/helpers/_fields.twig
=> Output fields in the order as specified in ContentType definition

phpstan.neon, src/Entity/FieldTranslation.php, src/Entity/TranslationInterface.php
=> Add our own TranslationInterface

src/Log/RequestProcessor.php
=> Log messages shouldn't have sensitive request info

assets/js/app/editor/Components/Slug.vue, config/bolt/contenttypes.yaml, src/Entity/Field/SlugField.php, templates/_partials/fields/slug.html.twig, translations/messages.en.xlf
=> Show correct Slug prefix when creating new content

src/DataFixtures/ContentFixtures.php, src/Entity/Field.php, tests/api/content/get_content.feature
=> Fix "Unable to generate an IRI for "Bolt\Entity\Field"."

src/Twig/LocaleExtension.php
=> Add `localdate` as an alias of `localedatetime`

assets/scss/layout/_admin.scss, assets/scss/modules/admin/_sidebar.scss
=> Resolve Z-index issue in file manager

Makefile
Helps to make the Travis log more readable.
=> runs selenium without output

src/Twig/BackendMenuExtension.php, templates/_base/layout.html.twig, templates/pages/menupage.html.twig
=> Rename admin_menu() twig function to admin_menu_array() for consistency

src/Twig/DebugExtension.php
See also https://github.com/bolt/docs/commit/90ef9561b22b733c2329358deb568884c432bcfd
Fixes #926
=> Implement `{{ dump(backtrace() }}`

assets/js/app/editor/Components/Image.vue, templates/_partials/fields/image.html.twig, tests/e2e/edit_record_1.feature
=> An image field can be removed/cleared once set

src/Entity/Field/ImageField.php, src/Entity/Field/MediaAware.php, src/Twig/ImageExtension.php
=> Fetching linked media for an Image field

src/Controller/TwigAwareController.php
=> Add support for `template_directory` in `theme.yaml`

src/Twig/TextExtension.php
=> Add `preg_replace` twig filter

src/Twig/JsonExtension.php
=> Add JSON Twig Test

src/Twig/HtmlExtension.php
=> Add Shy twig filter

.env.dist
=> Clarify database section in .env.dist a little

assets/js/app/editor/Components/File.vue, templates/_partials/fields/file.html.twig, tests/e2e/edit_record_1.feature
=> File field can be reset

config/routes.yaml, src/Controller/Frontend/DetailController.php, src/Entity/Field/SlugField.php, src/Repository/ContentRepository.php
=> Ensure slugs are not numerical, add example of route to allow access to records by number

src/Twig/RecordExtension.php, symfony.lock
Fixes #945 
PR for docs to match this, coming up.
=> Add Selected options formatting, plus enforce limit

src/Storage/Directive/OrderDirective.php, templates/content/listing.html.twig
=> Sort by author works

templates/_partials/fields/_label.html.twig, tests/e2e/edit_record_1.feature
=> Replace <icon> with <i> in infobox popover icon

src/Repository/ContentRepository.php, src/Twig/RelatedExtension.php
=> Use Bolt Query and remove findForListing

config/bolt/contenttypes.yaml, templates/content/listing.html.twig
(To stay in line with what's documented)
=> Tiny fix: Add description to ContentTypes

assets/js/app/editor/Components/Textarea.vue
=> Textarea.vue prop type fix

config/bolt/contenttypes.yaml
=> contenttypes.yaml includes correct examples with current field types

config/bolt/contenttypes.yaml
=> Fix formatting for `type: select`

src/Factory/MediaFactory.php
That's been on my list for some time...
=> MediaFactory knows jpeg is an image

assets/js/app/editor/index.js, assets/js/app/listing/index.js, assets/js/app/login/index.js, assets/js/app/sidebar/index.js
This fixes the Vue warning. Clean console log hurrah!
=> Only include Vue components if their containers exist on page

src/Twig/WidgetExtension.php, src/Widget/BaseWidget.php, src/Widgets.php
=> Implement missing utility functions for widgets

src/Twig/UserExtension.php
=> Implement `isallowed` twig function

run_behat_tests.sh
See if this reduces travis noise
=> Download selenium and chromedriver quietly

src/Controller/Backend/MediaController.php
Another one from SymfonyInsight
=> Flush EntityManager outside of loop

config/services_test.yaml, src/Log/LogHandler.php, src/Log/LoggerTrait.php, src/Twig/ContentExtension.php
Fixes another SymfonyInsight thingy.
=> Remove `dump()` from codebase

composer.json, config/bundles.php, config/packages/doctrine_migrations.yaml, config/services.yaml, src/Entity/Log.php, src/Migrations/Version20200219064805.php
=> Add migrations and `content_id` column to logging table

src/Configuration/Parser/ContentTypesParser.php, src/Entity/Content.php
=> Slug and Status are required, but not always set.

README.md
@bobdenotter What do you think about that?
=> Include status badges in README.md

.env.dist, config/packages/assets.yaml, config/packages/framework.yaml, config/packages/webpack_encore.yaml, config/services.yaml, src/Command/CopyAssetsCommand.php, src/Command/CopyThemesCommand.php, src/Configuration/Config.php, src/Configuration/PathResolver.php, src/Kernel.php, tests/php/Configuration/ConfigTest.php
=> Allow configuration of web root folder

src/Entity/Field.php, src/Entity/Field/TemplateselectField.php
=> Make sure templateselect is "stringable"

src/Storage/SelectQuery.php
=> Fetch multi-word contenttypes without  replacing hyphen

public/theme/skeleton/partials/_aside.twig, src/Configuration/Config.php, src/Storage/ContentQueryParser.php
=> Allow singular slug as CT in `setcontent`

config/bolt/contenttypes.yaml, src/Entity/Content.php, templates/_partials/fields/_base.html.twig
=> Set default status and default values on Record instantiation

templates/_partials/fields/password.html.twig
=> If strength == false, make sure it propagates to Vue component

src/Twig/ContentExtension.php
=> Omit Title in Excerpt by default

src/Event/Listener/ContentFillListener.php
=> Set Content publishedAt when status is published

assets/js/app/editor/Components/Image.vue, assets/js/app/editor/Components/Imagelist.vue, templates/_partials/fields/imagelist.html.twig
=> Support readonly on Imagelist

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Filelist.vue, templates/_partials/fields/filelist.html.twig
=> Support readonly on Filelist

composer.json, src/Controller/Backend/Async/UploadController.php
=> Update Sirius Uploader, get rid of raw `$_FILES`

config/bolt/contenttypes.yaml, src/Configuration/Parser/ContentTypesParser.php, src/Controller/Backend/ListingController.php, src/Controller/Frontend/ListingController.php, src/Storage/Directive/OrderDirective.php, tests/php/Configuration/Parser/ContentTypesParserTest.php
=> Sorting correctly for MySQL

src/Command/AddUserCommand.php, src/Utils/Validator.php
=> Make it more clear that regular users can't login

config/bolt/contenttypes.yaml
=> update one last `sort:` to `title:`

src/Configuration/Parser/ContentTypesParser.php, src/Controller/Frontend/SearchController.php, src/Repository/ContentRepository.php, tests/php/Configuration/Parser/ContentTypesParserTest.php
=> Only search in contenttypes that have `searchable: true`

src/Entity/Field/ImageField.php
=> Don't fill placeholders for ImageField if filename is not set.

src/Menu/BackendMenuBuilder.php, translations/messages.en.xlf
=> Make `show_in_menu` work as expected

src/Configuration/Content/FieldType.php, src/Configuration/Parser/ContentTypesParser.php, src/Entity/Content.php, templates/content/_fields.html.twig, tests/php/Configuration/Parser/ContentTypesParserTest.php
=> Don't show slugs for contenttypes without slugs

config/bolt/contenttypes.yaml, src/Twig/ContentExtension.php, src/Twig/RelatedExtension.php, src/Utils/ComposeValueHelper.php, templates/content/_relationships.html.twig
Uses the same format as the Select field for consistency.
=> Use compose value in Relations

src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php
Earlier I fixed the API values of Imagelists and Filelists, but it did not work for the ones that are not localized. This fixes that.
=> Imagelist and Filelist work in API if not localized

src/Controller/Backend/FileEditController.php, templates/finder/editfile.html.twig, translations/messages.en.xlf
=> Don't break when trying to save a file that's not writable

src/Configuration/Config.php, src/Controller/Frontend/TaxonomyController.php
=> Allow for taxonomy listings with singular Taxonomy Type slug

src/Canonical.php, src/Entity/Field/ImageField.php, src/Twig/ContentExtension.php
=> Image URL uses canonical config setting and take imagelist into account for the magic image

src/Entity/Content.php
=> Ensure we have 'slug' in API and 'getValues', even if none is set in contenttype.

src/Storage/Directive/PrintQueryDirective.php, src/Storage/Handler/SelectQueryHandler.php, src/Storage/SelectQuery.php
=> Allow `where` filtering on taxonomies in `setcontent`

src/Entity/Field.php
At least until we implement proper authentication for the other operations :-)
=> Only allow GET operations in API

src/Utils/TranslationsManager.php
Fixes issue with collections not being localizable, not quite sure when this was introduced as they used to work  🤷‍♂️
Fixes #1158
=> Fix issue with localized value in other locales removed from collection

src/Configuration/Parser/ContentTypesParser.php, src/Twig/ContentExtension.php, templates/content/listing.html.twig
Some follow-up tweaks to #1227
=> Make 'magic' titles and default sorting a bit more robust.

assets/js/app/editor/Components/Embed.vue, tests/api/get_content_fields.feature, tests/e2e/edit_record_1.feature
=> Embed field can be refreshed and cleared

src/Controller/Backend/ContentEditController.php
=> Don't "save" on preview

phpstan.neon, src/Controller/Backend/ContentEditController.php, src/Entity/Log.php, src/Event/ContentEvent.php, src/Event/Subscriber/ContentSaveSubscriber.php, templates/pages/logviewer.html.twig, translations/messages.en.xlf
=> Add Event for operations on Content. Clear cache for menu's. Log save after editing content.

config/bolt/contenttypes.yaml, src/Configuration/Parser/ContentTypesParser.php
=> Order by multiple fields

src/Collection/DeepCollection.php, src/Menu/FrontendMenuBuilder.php, templates/content/listing.html.twig, translations/messages.en.xlf, translations/messages.nl.xlf
=> Add "Create new …" button on listings, because otherwise you can't create new records in that contenttype.

src/Twig/ContentExtension.php
=> Record link filter persists current locale

src/Event/Subscriber/ContentSaveSubscriber.php, src/Menu/CachedBackendMenuBuilder.php, src/Menu/CachedFrontendMenuBuilder.php
=> Invalidate localized menu cache

src/Configuration/Parser/ContentTypesParser.php
Wonder why this wasn't picked up by phpstan?  🤔
=> Remove unused Bolt\Entity\Field import

public/theme/skeleton/partials/_recordfooter.twig, src/Twig/RelatedExtension.php, tests/spec/Bolt/Twig/RelatedExtensionSpec.php
=> Tidy up Twig RelatedExtension

assets/scss/layout/_admin.scss
See #902 
Same but for mobile too
=> Sidebar priority fixed on mobile too

src/Entity/ContentExtrasTrait.php, src/Twig/ContentExtension.php
See also https://github.com/bolt/docs/pull/1036
Fixes #1345
=> Add length attribute for `|title` filter

README.md
=> Update README - Note about `var/data/bolt.sqlite`

src/Command/ClearThumbnailCacheCommand.php, src/Command/InfoCommand.php, src/Command/ResetSecretCommand.php
=> Return correct exit status for cache:thumbs, bolt:reset-secret and bolt:info

templates/content/_buttons.html.twig
=> View saved version in current edit locale

composer.json, config/extensions/bobdenotter-configurationnotices.yaml, config/services_bolt.yaml, src/Extension/ServicesTrait.php
=> Add Configuration Notices extension

public/theme/skeleton/README.md, public/theme/skeleton/css/new.css, symfony.lock
=> Updates for skeleton theme

assets/js/app/editor/Components/Image.vue, assets/scss/init/_base.scss, config/bolt/config.yaml, src/Configuration/Config.php, src/Configuration/Parser/GeneralParser.php, src/Controller/Backend/Async/UploadController.php, src/Twig/TextExtension.php, templates/_partials/fields/file.html.twig, templates/_partials/fields/filelist.html.twig, templates/_partials/fields/image.html.twig, templates/_partials/fields/imagelist.html.twig, templates/finder/_files_actions.html.twig, templates/finder/_files_list.html.twig, translations/messages.en.xlf
=> Display upload limits and better feedback on failure

src/Entity/Field/CollectionField.php
=> Make sure you can iterate over collection with one field

src/Controller/ImageController.php
=> Allow x as well as × in thumbail URLs

composer.json, config/bundles.php, symfony.lock
=> Add `composer/package-versions-deprecated`

src/Configuration/Parser/ContentTypesParser.php
=> Forbid templateselect inside collection. Fix forbidden fields check.

src/Canonical.php, src/Twig/ContentExtension.php
=> Pretty record|link when localization is enabled

src/Storage/SelectQuery.php
=> Allow for parsed dates like "Today" or "in 3 weeks"

src/Entity/Content.php
=> Don't show Fields that were removed from the ContentType definition

assets/js/app/editor/Components/Text.vue
Follow-up for #1425
Fixes "slugification" part of #1437
=> Make sure editing text fields triggers slugify

src/Utils/LocaleHelper.php
=> Fix htmllang() when no locales defined

templates/_macro/_macro.html.twig, templates/_partials/fields/date.html.twig, templates/content/_buttons.html.twig, templates/users/listing.html.twig
=> Fix for windows not handling `%k` in timestamp strings properly

src/Utils/Html.php
=> Fix excerpt length

src/Event/Listener/FieldFillListener.php
=> Don't break on missing Collection Fields

assets/js/app/editor/Components/Image.vue, assets/js/app/editor/Components/Imagelist.vue, package.json, templates/_partials/fields/image.html.twig
=> Fix Imagelist alt 'true' issue. Clean up Vue components

src/Controller/Backend/Async/UploadController.php
=> Better check for maximum filesize

templates/content/_buttons.html.twig, templates/content/edit.html.twig
=> Hide one of two groups of record action buttons on mobile

src/Utils/LocaleHelper.php
Fixes #1487
@bobdenotter I don't know if I'd ever learn to differentiate between `has` and `contains` 🤦‍♂️
=> Fix current locale to be correct

assets/js/app/editor/Components/Image.vue
=> Placeholder in Image Field is not clickable if empty

src/Event/Listener/FieldFillListener.php, templates/_partials/fields/image.html.twig
=> Make sure sets inside collections are instantiated with actual values

templates/_partials/fields/date.html.twig
=> Datefield uses global app to access user locale

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Image.vue
=> [WIP] Warn editors about file upload errors

src/Storage/ContentQueryParser.php, src/Storage/Directive/OrderDirective.php, src/Storage/FrontendQueryScope.php, src/Twig/LocaleExtension.php, src/Utils/LocaleHelper.php
=> Use currently rendered locale in OrderDirective

assets/js/app/editor/Components/Slug.vue, assets/js/app/toolbar/Components/Toolbar.vue, templates/_partials/fields/slug.html.twig
=> Slugs follow localize setting

config/bolt/contenttypes.yaml, src/Configuration/Config.php, src/Controller/Frontend/HomepageController.php
=> Allow "Homepage" to be in viewless ContentType

config/services.yaml, src/Configuration/Content/FieldType.php, src/Event/Listener/ContentFillListener.php, src/Event/Listener/FieldFillListener.php, src/Repository/FieldRepository.php, templates/_macro/_macro.html.twig
Fixes #1559 by properly getting the definition for every field
Fixes #1555 
See #1568 (closed because of GitHub / Travis issues)
=> Ensure fields inside sets and collections have their correct definition

src/Controller/Backend/ContentEditController.php
=> Add defaultlocale to duplicate action twig

assets/scss/vendor/dropzone.scss, assets/scss/vendor/vendor.scss
Fixes #1522  + re-order vendor css in alphabetic order (since it seemed to cause no side effects)
=> Include proper css for file uploader

src/Controller/Backend/ContentEditController.php, templates/_partials/fields/slug.html.twig
=> Slug regenerates on duplicate

public/theme/skeleton/partials/_sub_taxonomylinks.twig, src/Entity/Taxonomy.php, src/Twig/ContentExtension.php
=> Use `taxonomy|link` filter to get taxonomy links

src/Repository/TaxonomyRepository.php
=> Use humanized taxonomy name when creating new taxonomies

assets/js/app/patience-is-a-virtue.js
=> Make sure form validation works with `data-patience` buttons

src/Storage/SelectQuery.php
`{% setcontent page = 'pages/2' %}` now returns Content
=> `setcontent` returns single for contenttype/id

assets/js/app/patience-is-a-virtue.js, config/bolt/config.yaml, phpstan.neon, public/theme/skeleton/partials/_sub_taxonomylinks.twig, src/Configuration/Parser/GeneralParser.php, src/Entity/Taxonomy.php, src/Repository/TaxonomyRepository.php, src/Twig/ContentExtension.php, src/Twig/FieldExtension.php, src/Twig/LocaleExtension.php, templates/_macro/_macro.html.twig, templates/_partials/fields/date.html.twig, templates/content/_fields_aside_summary.html.twig
=> Allow configurable `date_format` in config.yaml

src/Storage/Directive/OrderDirective.php, templates/_partials/notification.html.twig
=> Make the user-friendly notifications a bit more robust

src/Twig/UserExtension.php
=> Add `getuser` with alias `user` Twig function

assets/js/app/editor/Components/Select.vue, assets/scss/modules/editor/fields/_multiselect.scss
=> Make empty multiselect tag invisible

public/theme/skeleton/custom/setcontent_1.twig, src/Storage/Directive/RandomDirectiveHandler.php
Make sure random is always random :-)
=> Fix `setcontent` random directive to override anything else set by the OrderDirective

phpstan.neon, public/theme/skeleton/custom/setcontent_1.twig, src/Twig/ArrayExtension.php
=> Shuffle paginated records

src/Controller/ErrorController.php
=> Fix Errorcontroller adding Exception when it shouldn't.

composer.json, src/Entity/ContentExtrasTrait.php, src/Entity/Field.php, src/Twig/ContentExtension.php, src/Utils/Sanitiser.php, symfony.lock
=> Make Sanitiser obey allowed tags and attributes from `config.yaml`

src/Configuration/Content/FieldType.php, templates/content/_fields.html.twig, templates/helpers/_field_blocks.twig
=> Allow for extensions to add new FieldTypes

translations/messages.de.xlf, translations/validators.de.xlf
Added various German translations by using the debug tool, as described in https://github.com/bolt/core/wiki/Contribute-on-translations
=> added various German translations

src/Controller/Backend/ContentEditController.php
Fixes localization part of #1653 (sets can be localized)
=> Fix set field being localizable

src/Controller/ImageController.php, src/Entity/Field/FileExtrasTrait.php, src/Entity/Field/FileField.php, src/Entity/Field/ImageField.php, tests/api/get_content.feature
=> Add image.extension value

src/Controller/ImageController.php, src/Utils/ThumbnailHelper.php
=> Prettify thumbnail paths. Use Bolt 4 cropping options

templates/content/view_locales.html.twig
=> Show detailed localization for fields containing subfields

src/Configuration/Parser/TaxonomyParser.php, tests/php/Repository/TaxonomyRepositoryTest.php
=> Do _not_ use taxonomy values. Use them as defined

templates/helpers/_menu.html.twig
=> Fix menu `item|current` in _menu.html.twig

src/Utils/ThumbnailHelper.php
=> Thumbnailing works with only width or only height

src/Entity/Relation.php, src/Factory/RelationFactory.php, src/Repository/RelationRepository.php, src/Twig/RelatedExtension.php
=> Refactor relations to be properly bidirectional

config/bolt/config.yaml, config/services.yaml, src/Configuration/Parser/GeneralParser.php, src/Entity/Field/CheckboxField.php, src/Entity/Field/CollectionField.php, src/Entity/Field/FileField.php, src/Entity/Field/FilelistField.php, src/Entity/Field/HiddenField.php, src/Entity/Field/ImageField.php, src/Entity/Field/ImagelistField.php, src/Entity/Field/RawPersistable.php, src/Entity/Field/SelectField.php, src/Entity/Field/SetField.php, src/Event/Listener/FieldFillListener.php, src/Utils/Sanitiser.php
=> Improve Sanitiser. Sanitise fields on save.

composer.json, src/Command/ExtensionsConfigureCommand.php
=> Remove services before `composer remove`

ecs.php, src/Twig/TextExtension.php
=> Add `url_decode` Twig Filter

src/Twig/CommonExtension.php
=> Current filter works for locale

public/theme/skeleton/custom/setcontent_1.twig, src/Storage/ContentQueryParser.php, src/Storage/Directive/PageDirective.php, src/Storage/Handler/SelectQueryHandler.php, src/Twig/TokenParser/SetcontentTokenParser.php, tests/php/Twig/SetcontentTokenParserTest.php
```
{% setcontent records = 'entries' page 4 %}
```
=> New `page` directive for setcontent to override the current page setting

templates/helpers/_field_blocks.twig
=> Add "Number" and "Date" fields

public/theme/skeleton/custom/setcontent_1.twig, src/Storage/SelectQuery.php
=> For now, only use setcontent with standalone fields

public/theme/skeleton/custom/setcontent_1.twig, src/Doctrine/Version.php, src/Storage/Directive/OrderDirective.php
=> Better check for `INSTR` and `CAST`

src/Storage/Directive/OrderDirective.php
=> Fix orderby non-localizable field in localized contenttype

config/bolt/config.yaml, src/Configuration/Parser/GeneralParser.php, src/Controller/Frontend/ListingController.php, src/Storage/Handler/SelectQueryHandler.php
=> Filter and order using queryparams on listing pages

src/Storage/SelectQuery.php
e.g. `{% setcontent pages = 'pages' where { 'id': '>50' } %}` should not return a single record, even if it's filtering by ID.
=> shouldreturnsingle handles id filtering based on operator

config/services.yaml, translations/messages.cs.xlf, translations/security.cs.xlf, translations/validators.cs.xlf
=> WIP: Czech localization

templates/content/edit.html.twig
=> Show appropriate `displayTitle` for new "Singleton" Record

assets/js/app/editor/Components/Embed.vue, src/Utils/Sanitiser.php
=> Allow src in iframes for embeds to work. Add spinner feedback while embed is loading.

src/Configuration/Parser/ContentTypesParser.php
=> Add pattern `url` and `email` options as shown in the docs

.travis.yml, assets/js/app/editor/Components/Filelist.vue, assets/js/app/editor/Components/Imagelist.vue, ecs.php, templates/helpers/_taxonomylinks.html.twig
Looks like I can't git either 🙈
Why does this travis_retry commit keep popping up!!
=> Imagelists and Filelists work in collections

assets/js/app/editor/Components/Collection.vue, templates/_partials/fields/collection.html.twig
=> Multiple collections buttons don't break on the same page

src/Controller/Backend/MediaEditController.php
=> Don't show `Media created successfully` if it's not new

templates/_partials/fields/textarea.html.twig
=> Edit attributes button does not break the page.

assets/js/app/editor/Components/Select.vue, assets/scss/vendor/multiselect.scss
https://github.com/bolt/redactor/issues/3
=> Make z-index of `<select>` a bit higher

config/bolt/contenttypes.yaml, src/Controller/Frontend/DetailController.php, src/Entity/Field/SlugField.php
Fixes #1877 
This one's for you, @eduardomart 😘
=> Allow numeric slugs with `allow_numeric` attribute in ContentType

assets/scss/vendor/multiselect.scss
Fix #1888, revert #1875
see also https://github.com/bolt/redactor/pull/4
=> Fix Z-index, attempt 2

templates/content/_buttons.html.twig
=> Only show "Preview" button if ContentType is not Viewless

src/Configuration/Parser/GeneralParser.php, src/Twig/FieldExtension.php, src/Twig/LocaleExtension.php
Fixes #1581
Fixes #1898 
Fixes #1894
=> Getting a date uses the default timezone from config

translations/messages.fr.xlf, translations/security.fr.xlf, translations/validators.fr.xlf
Change the french translation in the translations folder to provide full translate
=> Feat : add French Translations

src/Entity/Field/FileExtrasTrait.php, src/Entity/Field/FileField.php, src/Entity/Field/ImageField.php
=> Empty image Field should return `null` instead of `files/`

assets/js/app/editor/Components/Collection.vue, assets/scss/modules/editor/fields/_collection.scss, templates/_partials/fields/_collection_buttons.html.twig, tests/e2e/edit_record_1.feature, translations/messages.en.xlf
=> Ensure the "Titles" in collection blocks are plain text only

src/Storage/SelectQuery.php
=> Ignore empty like `%%` parameters

phpstan.neon
Low hanging fruit cherry-pick from https://github.com/bolt/core/pull/1919/files
=> [phpstan] remove invalid tmp dir + dependency on symfony container

composer.json
cherry-picked from https://github.com/bolt/core/pull/1918
=> [composer] remove copy-paste leftovers

translations/messages.zh_CN.xlf, translations/security.zh_CN.xlf, translations/validators.zh_CN.xlf
Chinese translation Initial submission.
=> Simplified Chinese translation

src/Controller/Backend/ListingController.php
=> Redirect to record or new record on singleton listing pages in backend

assets/js/app/listing/Components/SelectBox.vue, templates/content/listing.html.twig
=>  Fix url for 'bulk' operations on Listing screen, for sites with modified Backend URL

src/Configuration/Parser/ContentTypesParser.php, src/Entity/FieldParentTrait.php
=> Any field that has a localized field down the line is considered localized

translations/messages.hu.xlf, translations/validators.hu.xlf
Following v4 release updated .hu translations.
=> Missing HU labels

assets/js/app/editor/Components/Collection.vue
=> Don't repeat "Add to collection" text when there's only one

config/packages/twig.yaml
See https://github.com/bolt/project/pull/37
=> Enable twig namespace 'theme' by default

src/Command/ExtensionsListCommand.php
=> Fixed Extensions List Command issue with package name

translations/messages.tr.xlf, translations/security.tr.xlf, translations/validators.tr.xlf
Turkish translations support for bolt 4
=> add Turkish translations

translations/messages.el.xlf, translations/security.el.xlf, translations/validators.el.xlf
=> Add Greek EL translations

phpstan.neon
Thanks for the suggestion, @LordSimal ! 👍
=> Add `Carbon` to `scanDirectories`

config/packages/twig.yaml
=> Access `defaultLocale` in twig

config/bolt/config.yaml
=> Correct spelling of `sup`

src/Command/InfoCommand.php
Fixes #1969 
Fixes https://github.com/bolt/project/issues/44
=> Don't break installation if SQLite is not present

templates/_partials/fields/imagelist.html.twig
=> Fix empty Imagelist breaking rendering in Prod ENV

assets/js/app/editor/Components/Select.vue, templates/content/_relationships.html.twig
Special thanks to @nestordedios for spotting this and resolving it :-)
=> Searchable relations

src/Kernel.php, src/Repository/FieldRepository.php, src/Twig/FieldExtension.php
Fixes #2030 
But it runs on every request.
=> Correctly instantiate fields in prod

config/bolt/contenttypes.yaml, templates/_partials/fields/checkbox.html.twig
=> Readonly checkbox + switch option

assets/scss/modules/filemanager/filemanager.scss, assets/scss/modules/modules.scss, src/Controller/Backend/FilemanagerController.php, templates/_partials/fields/_base.html.twig, templates/finder/_createfolder.html.twig, templates/finder/_folders.html.twig, templates/finder/finder.html.twig, tests/e2e/filemanager.feature, translations/messages.en.xlf
Part of #2101 
Desing-wide feedback is much appreciated ;)
=> Filemanager create/delete folder actions

src/Twig/ContentExtension.php, templates/content/_buttons.html.twig
=> Show preview button on Homepage, even if viewless

bin/composer-script/post-install-cmd.php, bin/composer-script/post-update-cmd.php, bin/composer-script/run.php
Fixes #2002 + it provides output if a command actually fails.
=> Configure extension config on install and update + more output when something fails

Makefile, docker/php/Dockerfile
=> Enhanced docker build

src/Controller/Frontend/ListingController.php
Fixes https://github.com/bolt/core/issues/2109
=> return 404 for listing route of contenttype that has viewless: true

translations/messages.ru.xlf
Adding a few new labels for russian translations
=> add additional labels

src/Configuration/Parser/ThemeParser.php, src/Twig/ContentExtension.php
Fixes #2070 
This one is for you, @peterboorsma ! 🥳
=> Use correct template directory in templateselect

assets/js/app/editor/Components/Collection.vue
=> Show field label inside collection

src/Twig/FieldExtension.php
=> `|selected` filter orders by the value of the select

templates/_partials/fields/set.html.twig
Don't ask me why a set inside a set works 🙈
=> Set inside set displays properly

src/Twig/ContentExtension.php, src/Twig/FieldExtension.php
As it was in Bolt3...
Implements #2132
=> add keys setting for select field type

assets/js/app/editor/Components/Select.vue
=> Fix searchable relations

templates/security/login.html.twig
@bobdenotter Now it is right-aligned 😋
=> Move 'Forgot password' link to the right

src/Twig/ContentExtension.php
=> Sort templateselect alphabetically

assets/scss/modules/base/_badges.scss, src/Controller/Backend/ListingController.php, templates/content/listing.html.twig, translations/messages.en.xlf
=> Show 'quick links' to taxonomies in the sidebar of listings

src/Configuration/Parser/GeneralParser.php
=> Set defaults for avatar settings

src/Command/WelcomeCommand.php
=> Create Welcome command

assets/js/app/toolbar/Components/Toolbar.vue, templates/_base/layout.html.twig
Little improvement, but looks nice :-)
=> Show the user avatar in the toolbar, if it exists

src/Twig/FieldExtension.php
This actually returns a sane PHP array 😳
=> Fix issue with sorting order for `|selected`

src/DataFixtures/ContentFixtures.php, src/Storage/QueryParameterParser.php
=> Add welcome to theme

src/Controller/Backend/ContentEditController.php
Retry of #2223 after I messed it up. 🙈
=> Don't break if a set's definition no longer contains a field

templates/helpers/_pager_tailwind.html.twig
=> Support tailwind pager for base-2021

composer.json, config/bundles.php, config/packages/doctrine_migrations.yaml, migrations/Version20201210105836.php, symfony.lock
@bobdenotter does this OK to you?
=> Prepare migrations for 4.2

src/Entity/Field/MarkdownField.php
=> Don't sanitise markdown fields

templates/helpers/_pager_basic.html.twig, templates/helpers/_pager_bulma.html.twig, templates/helpers/_pager_tailwind.html.twig
I messed up #2252....🙈  'is what happens when you can't git...
Fixes #2251
=> Pager `Previous` and `Next` are localized labels. `active` state for basic pager.

templates/content/listing.html.twig
=> Fix escaping of ContentType names in listing pages

src/Configuration/Parser/GeneralParser.php
=> Set `base-2020` in `GeneralParser.php`

composer.json, package.json, src/DataFixtures/BaseFixture.php, src/DataFixtures/ImageFetchFixtures.php, symfony.lock
In my tests it's about 3 times as fast as before: 
Before: 
```
time bin/console doctrine:fixtures:load -n
> purging database
> loading Bolt\DataFixtures\UserFixtures
> loading Bolt\DataFixtures\TaxonomyFixtures
> loading Bolt\DataFixtures\ImageFetchFixtures
20/20 [============================] 100%
> loading Bolt\DataFixtures\ImagesFixtures
> loading Bolt\DataFixtures\ContentFixtures
> loading Bolt\DataFixtures\RelationsFixtures
bin/console doctrine:fixtures:load -n  2.13s user 0.60s system 10% cpu 27.108 total
```
After: 
```
time bin/console doctrine:fixtures:load -n
> purging database
> loading Bolt\DataFixtures\UserFixtures
> loading Bolt\DataFixtures\TaxonomyFixtures
> loading Bolt\DataFixtures\ImageFetchFixtures
100/100 [============================] 100%
> loading …
```
=> Feature/use placeholder.boltcms.io

src/Entity/Field.php, src/Event/Listener/ContentFillListener.php, src/Twig/ContentExtension.php
One less `Request::createFromGlobals()` :innocent:
=> Fix allow twig and deprecate `record|allow_twig` requirement

src/Command/WelcomeCommand.php
This bugfix goes against the `master` branch
=> Fix welcome command explanation

src/Entity/Field/SelectField.php
=> Fix `default` option for select field

src/Menu/BackendMenuBuilder.php
=> Make sure Other Content works on mobile

src/Controller/Backend/ContentEditController.php
For example:
`/pages/about-us` => `/bolt/edit/pages/about-us` ✅ 
`/en/pages/about-us` => `/bolt/edit/en/pages/about-us` ✅ 
`/about-us` => `/bolt/edit/about-us` ✅ 
`/en/about-us` => `/bolt/edit/en/about-us` ✅
=> Reach backend edit by prepending `/bolt/edit/` to current page's URL

templates/content/_buttons.html.twig
Make sure you don't close the tab, losing all outstanding changes
=> Open secure link new tab

src/Storage/QueryParameterParser.php
=> Fix setcontent query for checkbox `false` values

assets/js/app/editor/Components/Slug.vue, assets/js/app/editor/Components/Textarea.vue, assets/js/app/listing/Components/Table/Row/index.vue, assets/js/app/toolbar/Components/Toolbar.vue, assets/scss/init/_variables.scss, src/Event/Listener/FieldDiscriminatorListener.php, templates/_base/layout_blank.html.twig, templates/content/listing.html.twig, translations/messages.nl.xlf, translations/validators.nl.xlf
=> Dashboard editor accessibility fixes. Several Dutch 🇳🇱  labels

templates/_partials/fields/select.html.twig
Implements #2215
Just added forwarding for searchable prop in twig template
=> Issue 2215 searchable select

src/Controller/ErrorController.php
=> Redirect to Bolt Dashboard if 403 response comes from the Editor

src/Command/InfoCommand.php, src/Event/Listener/FieldDiscriminatorListener.php
=> Show warning for outdated `composer.json` for 4.2

src/Controller/Backend/Async/EmbedController.php
=> Fix YouTube oEmbed missing `title` accessibility issue

src/Twig/ImageExtension.php
With special thanks to @mcdennem for working with me to find and fix this
=> Fix `record|thumbnail` getting different image than `record|image`

public/.htaccess
Special thanks to @bigz for reporting this issue. Thank you for your cooperation! 👍
=> Forbid certain theme files from public exposure

src/Form/FieldTypes/PasswordWithPreviewType.php, src/Form/LoginType.php, templates/form/fields.html.twig
Fixes #2316 the proper Symfony forms way :-)
_Taking 5 times the effort and time, because documentation..._
=> Toggle password on login fixed for Symfony forms

composer.json, src/Twig/ContentExtension.php
=> Use TemplateSelect `filter` option with directories

src/Configuration/Parser/ContentTypesParser.php
https://insight.symfony.com/what-we-analyse/php.boolean_statement
=> Replace `and` with `&&`

assets/js/app/editor/Components/Email.vue
=> Show an envelope icon for email fields to distinguish from text

src/Controller/ErrorController.php
https://insight.symfony.com/what-we-analyse/symfony.dependency_injection.no_container_as_parameter
=> Refactor `ErrorController` by replacing container dependency with `ParameterBagInterface`

src/Controller/Backend/UserEditController.php, src/Utils/FlagMaster.php
https://insight.symfony.com/what-we-analyse/php.psr1
=> Use PSR-1 basic coding standard for method names

composer.json, config/packages/test/security.yaml, tests/e2e/login.feature
=> Fix slow tests

src/Repository/RelationRepository.php
=> Remove incorrect `PHPDoc @var` tag in RelationRepository

src/Entity/Field/CollectionField.php, src/Entity/Field/FilelistField.php, src/Entity/Field/ImagelistField.php, src/Entity/Field/SelectField.php, src/Entity/Field/SetField.php, src/Entity/IterableFieldTrait.php
=> Make multiselect fields iterable in Twig

src/Entity/Content.php
This is step 1 to making sure the content exporter works properly with CSVs.
=> Content `toArray()` method returns fields according to definition

composer.json, src/Controller/Backend/ContentEditController.php
Depends on https://github.com/bolt/common/pull/35
(And also I think I might look into a bit more refactoring of this before merging in)
=> `ContentEditController` cleanup

assets/js/app/editor/Components/Date.vue
=> Fix date field with `required: true`

assets/scss/modules/admin/_sidebar.scss
=> Ensure sufficient contrast ratio for Editor sidebar text

config/bolt/permissions.yaml, src/Event/Subscriber/MaintenanceModeSubscriber.php, src/Event/Subscriber/WidgetSubscriber.php, src/Security/GlobalVoter.php, src/Widget/MaintenanceModeWidget.php, templates/widget/maintenance_mode.twig, translations/messages.en.xlf
Fixes #1883 in the master branch, due to the new permissions feature.
=> `ROLE_ADMIN` can access site in maintenance mode

src/Configuration/Config.php
=> Keep cache timestamps for all `.env` files

src/Event/Listener/FieldFillListener.php
Special thanks to @nestordedios for solving this weirdness!
=> Don't break collection looping if definition changes

src/Twig/ImageExtension.php
=> Use `symfony/assets` URL generation for assets in `ImageExtension.php`

bin/composer-script/ProjectEventHandler.php
=> Add project update/install callables

templates/_partials/fields/file.html.twig, templates/_partials/fields/filelist.html.twig, templates/_partials/fields/image.html.twig, templates/_partials/fields/imagelist.html.twig
=> Remove direct references to fields from twig templates

.github/workflows/a11y_tests.yaml, .github/workflows/behavioural_tests.yaml, .github/workflows/code_analysis.yaml, .github/workflows/unit_tests.yaml
Similar to #2448, but also for the accessibility tests.
=> Update `shivammathur/setup-php` to v2 for accessibility

bin/composer-script/PostUpdateScript.php
=> Run yaml migrations on `composer update`

src/Controller/Frontend/ListingController.php
Fixes #1990
(Both for singletons, as well as for listing pages)
=> Don't break if listing pages have extra parameters

src/Controller/Frontend/ListingController.php
=> Improve parameter override for Listing Pages

src/Command/AddUserCommand.php
Example:
`php bin/console bolt:setup ivo my_password ivo@example.org Ivo --roles=ROLE_ADMIN --roles=ROLE_USER --roles=ROLE_FOO` as well as interactive.
=> Allow `--roles` option using the `bin/console bolt:add-user` command

assets/js/app/editor/Components/Date.vue, assets/scss/init/_variables.scss, assets/scss/modules/editor/_label.scss, templates/content/_tabs.html.twig
Hi!
This PR adds some changes to green buttons, text on disabled input fields and adds some aria-label and role attributes for a better score on accessibility. On Google Lighthouse scanner we go from 63 to 85 points.
Fixes #1994
=> Merge accessibility fixes into master

assets/scss/init/_base.scss, assets/scss/init/_variables.scss
=> Pretty code tags in the Editor

src/Command/ListUsersCommand.php, templates/users/listing.html.twig, tests/e2e/users.feature, translations/messages.en.xlf
=> Adding "Edit Permissions" button, applying spit-polish to "Edit users" screen

src/Controller/Frontend/ListingController.php
That's one of the things that would be good to have a test for, perhaps 🤔
=> Fix bug where `anyField` search no longer works on listing

src/Entity/User.php
=> Assert User's email is not blank

ecs.php
=> Suppress unneeded notices in ECS

bin/composer-script/CreateProjectScript.php, bin/composer-script/PostInstallScript.php, bin/composer-script/PostUpdateScript.php, bin/composer-script/PrePackageUninstallScript.php, bin/composer-script/ProjectEventHandler.php, bin/composer-script/Script.php, src/Command/InfoCommand.php
=> Don't run migrations in composer scripts, if the Database is not initialised yet.

Makefile, src/Command/SetupCommand.php
=> Initialise Doctrine Migration table, make command less noisy

composer.json, src/Utils/ContentHelper.php
=> Decode HTML entities in `title_format` and related

src/Controller/Backend/ContentEditController.php
=> not remove reverse relation when save

templates/users/_form.html.twig
=> Escape password, to not break the page's HTML

src/Utils/LocaleHelper.php
=> Locale get link always `_locale` parameter

assets/js/app/listing/Components/Filter.vue, templates/_partials/_content_listing.html.twig, translations/messages.en.xlf
Added a text to the select all checkbox on admin listing pages. This will fix issue 2177.
=> 2177: Add SR only text to select all checkbox

src/Command/CopyThemesCommand.php, src/Extension/ExtensionRegistry.php
=> Fix copy-themes with packages. Implement copying specific theme

src/Entity/Content.php, src/Entity/Field.php, src/Event/Listener/ContentFillListener.php, src/Kernel.php
Also allows to use the `record` global variable in fields with `allow_twig`
=> Autowire twig environment to Field for rendering

src/Controller/Backend/ContentEditController.php
Makes several methods public for use in the conimex extension.
=> [WIP] Make field update methods temporarily public

templates/users/listing.html.twig
=> Fix link to edit permissions page in users listing page

composer.json, config/services.yaml, symfony.lock, yaml-migrations/m_2021-06-04-services.yaml
See https://github.com/jasny/twig-extensions
=> Adding Jasny Twig Extensions for Bolt 5.

config/bolt/config.yaml, src/Configuration/Parser/GeneralParser.php, src/Controller/Frontend/ListingController.php
#2621 
@nestordedios next time, doing that will be less hacky ;-)
=> Add `ignore_empty` option in `query_search` listing filtering

phpstan.neon, src/Storage/ContentQueryParser.php, src/Storage/Directive/OrderDirective.php, src/Storage/FieldQueryUtils.php, src/Storage/FrontendQueryScope.php, src/Storage/SelectQuery.php
=> Filter by numeric fields in `setcontent`

src/Storage/ContentQueryParser.php, src/Storage/Directive/DirectiveHandler.php, src/Storage/FrontendQueryScope.php
=> Decouple directive handling from the `ContentQueryParser`

src/Doctrine/Version.php, src/Storage/SelectQuery.php
Fixes issues with number field types in query parameters showing as a json array and not directly comparable as numbers. Further issues with cast detection fixed.
Fixes: #2620
=> Additional Filter / Order By Number Field Types Fix

src/Doctrine/JsonHelper.php, src/Storage/SelectQuery.php
=> Don't lowercase values in queries, allow for booleans

src/Configuration/Parser/ContentTypesParser.php
=> Replace `_` with space in Field labels

src/Storage/Directive/OrderDirective.php
=> Allow whitespace in `orderby` in setcontent queries

src/Controller/Backend/AuthenticationController.php, src/Form/LoginType.php
This is  #2715, but for Bolt 5.0.
=> [5.x] Simplify, don't mangle username on incorrect input for Login

src/Factory/ContentFactory.php
And here's the docs PR: https://github.com/bolt/core/pull/2726/files
=> Add a ContentFactory with static and dynamic create and upsert

src/Controller/ImageController.php
=> Throw 404 response when thumbnailing a missing image

bin/composer-script/CreateProjectScript.php
=> Run `bin/console bolt:reset-secret` when creating a new project

README.md, SETUP.md
[Preview](https://github.com/bolt/core/tree/repo/enhanced-readme)
=> Create a new readme

src/Configuration/Config.php, templates/finder/_uploader.html.twig, templates/pages/about.html.twig
=> Improve feedback for uploading files

bin/composer-script/Script.php
Fixes #2751 
Thanks to @DamShaa for bringing up the issue.
=> Use Symfony Process component instead of `passthru`

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Image.vue, assets/js/app/editor/Components/Text.vue, assets/scss/init/_variables.scss, templates/_partials/fields/_base.html.twig, templates/content/_buttons.html.twig, templates/finder/editfile.html.twig, templates/pages/logviewer.html.twig, tests/a11y/pa11yci.json, tests/cypress/integration/edit_record_1_content.spec.js, tests/cypress/integration/edit_record_1_fill_set_collection.spec.js
@stelakasabova's accessibility improvements + csfix and test fixes
=> Improve accessibility names, ids and labels

templates/helpers/page_404.html.twig
=> Add helpful notice to 404 exception page

config/bolt/permissions.yaml
=> Fine-tune default permissions

assets/js/app/editor/Components/Textarea.vue, templates/_partials/fields/textarea.html.twig
ID was missing for the textarea which broke the label.
=> Fix missing id for textarea

src/Entity/Relation.php, tests/php/Entity/RelationTest.php
Added ?int for return type of Relation getId().
=> Added possible null return for getId. Closes #2834

templates/helpers/_pager_basic.html.twig
Default pager didnt render the ellipsis because it was missing a definition for path
=> Fixed not rendering ellipsis

assets/js/app/editor/Components/Password.vue
=> Fixed issue about the password eye

src/Entity/Content.php, src/Event/Subscriber/ContentSaveSubscriber.php, src/Twig/JsonExtension.php
Another part split off from #2853
This one in particular speeds up listings in the Bolt Backend.
=> Cache JSON encoding of an array of Entries

templates/_partials/fields/_label.html.twig
=> Fix UX issue #2899

src/Security/LoginFormAuthenticator.php, src/Security/LogoutListener.php
(marked as DRAFT, because it's probably going to clash what @I-Valchev 's working on)
=> More detailed logging when logging in and logging out

src/Event/Listener/ContentFillListener.php
=> Fix unique slugs if title is empty

templates/content/_fields.html.twig
Such a nice little feature, great suggestion for how to do it @bobdenotter 🙌
=> Allow overriding field twig templates

assets/scss/modules/editor/fields/_pre_postfix.scss
Fixes #2910 
this how it looks now
=> Fix the postfix css

src/Command/WelcomeCommand.php
There was a typo in the welcome command
=> Little typo :)

assets/js/app/listing/Components/SelectBox.vue, assets/js/app/toolbar/Components/Toolbar.vue, templates/_base/layout.html.twig, templates/content/listing.html.twig
This commit stops Admin Toolbar to dissapear when bolt.backend_url includes subfolder
Fixes #2932
=> fix 2932 prop backendPrefix cause empty toolbar

tests/cypress/README.md
Hope this helps with running them locally instead of waiting for the ones from the pull requests 😄 
Linked issue: #2936
=> Update Cypress's README.md

config/bolt/contenttypes.yaml, src/Configuration/Parser/ContentTypesParser.php
=> Fix regex for email pattern

assets/scss/modules/editor/fields/_multiselect.scss
=> Fix content jumping when selecting a value from select

config/routes.yaml
Full credits, alongside with the original commit, to @nestordedios ☺️
Fixes #2948
=> Fix contenlisting sample route

composer.json
=> Fix getting db version (lock `doctrine/dbal`)

tests/cypress/integration/bulk_actions.spec.js, tests/cypress/integration/display_record.spec.js, tests/cypress/integration/display_record_test.spec.js, tests/cypress/integration/display_taxonomies.spec.js, tests/cypress/integration/edit_record_1_change_title.spec.js, tests/cypress/integration/edit_record_1_content.spec.js, tests/cypress/integration/edit_record_1_field.spec.js, tests/cypress/integration/edit_record_1_fill_list.spec.js, tests/cypress/integration/edit_record_1_fill_set_collection.spec.js, tests/cypress/integration/edit_record_2.spec.js, tests/cypress/integration/edit_users.spec.js, tests/cypress/integration/editor_permissions.spec.js, tests/cypress/integration/filemanager.spec.js, tests/cypress/integration/frontend_menu.spec.js, tests/cypress/integration/record_listing.spec.js, tests/cypress/integration/record_localization.spec.js, tests/cypress/integration/setcontent.spec.js, tests/cypress/integration/user_permissions.spec.js, tests/cypress/integration/view_users_tables.spec.js, tests/cypress/support/index.js
=> Remove some of the describe from Cypress / Fix some common Cypress errors

config/services.yaml, src/Twig/AssetsExtension.php, yaml-migrations/m_2021-12-10-services.yaml
=> Fallback to Symfony's default public path for bundles

composer.json, symfony.lock
=> PHP 8.1 compatibility

config/bolt/permissions.yaml, public/theme/skeleton/custom/setcontent_1.twig, src/Controller/Backend/ContentEditController.php, src/DataFixtures/UserFixtures.php, src/Doctrine/Version.php, src/Storage/Directive/OrderDirective.php, src/Storage/FieldQueryUtils.php, src/Twig/ContentExtension.php, templates/_macro/_macro.html.twig, templates/content/_taxonomies.html.twig, tests/cypress/cypress-dev.json, tests/cypress/integration/chief_editor_permissions.spec.js, tests/cypress/integration/setcontent.spec.js
=> Port the has sortorder for taxonomies 3001

.github/workflows/api_tests.yaml
Adding curl-based tests for the new API
See https://github.com/bolt/project/pull/106 for context.
=> Add curl API tests

src/Twig/RelatedExtension.php
https://github.com/bolt/core/issues/3051
=> Bugfix Fix `maximum_listing_select` in `config.yaml` for Relation

src/Configuration/Config.php
https://github.com/bolt/core/issues/3067
=> Fix configuration values not resolving correctly

src/Controller/Backend/FileEditController.php
=> Fixes yaml parsing for services.yaml

src/Controller/Frontend/HomepageController.php
=> Fix custom homepage setting: allow singular ContentType slugs

tests/cypress/cypress-ci.json, tests/cypress/cypress-dev.json
For more info see:
[https://docs.cypress.io/guides/guides/test-retries#Global-Configuration](https://docs.cypress.io/guides/guides/test-retries#Global-Configuration)
=> Update cypress tests so it retries on failure

src/Cache/CachingTrait.php, src/Cache/SelectOptionsCacher.php
=> Bugfix: verify setting correct tags for caching works correctly

src/Repository/FieldRepository.php
Fixes #3140, thanks @simongroenewolt
=> Remove unused method

src/Menu/BackendMenuBuilder.php
=> feature(backend-menu): make top level menu icon customizable

src/Entity/Field/HiddenField.php
=> feature(field-type): make hidden field usable

src/Menu/BackendMenuBuilder.php
=> fix(backend-menu): parent menu items use wrong icon

.github/workflows/cypress_tests.yaml, tests/cypress/cypress-ci.json, tests/cypress/cypress-dev.json, tests/cypress/integration/widgets.spec.js
[Failed tests](https://github.com/bolt/core/actions/runs/2154194621)
=> Add videos to cypress evidence

templates/_partials/fields/set.html.twig
This will fix custom fields inside sets
=> Fixed the custom field type inside sets

tests/cypress/README.md
This update is to give a more clear explanation of what cypress evidence is and where to find it.
=> Update Cypress readme

assets/js/app/editor/Components/Collection.vue, config/bolt/config.yaml, config/services.yaml, src/Cache/FilesIndexCacher.php, src/Controller/Backend/Async/FileListingController.php, src/Controller/Backend/Async/UploadController.php, src/Utils/FilesIndex.php, yaml-migrations/m_2022-04-10-services.yaml
If I'm not mistaken, in Bolt CMS we can't render images in the modern .webp format "out-of-the-box". In any case i have not found such information anywhere.
=> Render .webp images

src/Controller/TwigAwareController.php
Separate parameters build from pager build. Allows a level of flexibility.
=> Separate methods for pager from pagerParams.

src/Canonical.php
=> Ensure correct canonical

assets/js/app/editor/Components/Image.vue, templates/content/_taxonomies.html.twig, templates/content/edit.html.twig
=> Fix rendering of save button on every tab-pane

assets/js/app/editor/Components/Image.vue
This PR fixes:
- Missing input field to upload an image from URL
- Console error that appear when opening and closing the modal to upload an image from a URL
On this branch I can't reproduce #3225 and #3226 so updating to the latest Bolt version should get those fixed.
Fixes #3225 and fixes #3226
=> Fix upload from url

assets/scss/layout/_admin.scss
=> Increase textarea field font-size

assets/js/app/editor/Components/Collection.vue
Fixes #3264 
Detect if the save button is clicked and remove the collection item then.
=> Remove collection item if the user accepts

assets/js/app/editor/Components/File.vue, assets/js/app/editor/Components/Image.vue, src/Controller/Backend/Async/FileListingController.php, src/Utils/FilesIndex.php
Fixes #3269 
This PR fixes some quirks with the navigation of images/files in modals. It also sets the right paths for to the selected image in the input field.
=> Fix modal images navigation

src/Menu/BackendMenuBuilder.php
=> Fix icons in ContentTypes in Menu

src/Controller/Backend/Async/UploadController.php
Thanks to Eitan at [WhiteSource](whitesourcesoftware.com) for responsibly disclosing this issue to us. 🙏
=> Ensure uploaded SVG files have no embedded Javascript

src/Storage/SelectQuery.php
Fixes #3186. Fix deprecation notice in PHP8.0 and above
=> Issue: #3186. Fix deprecation notice in PHP8.0 and above

src/Storage/SelectQuery.php
=> Remove outdated edge-case, that was actually breaking on MariaDB

src/Entity/Field/CollectionField.php, src/Entity/Field/SetField.php
=> The `|excerpt-filter` now also excerpts fields inside Collections and Sets

config/bolt/config.yaml
=> Allow editing YAML files through the Bolt Backend

bin/composer-script/PostUpdateScript.php
Remove .php ending of fix-bundles script #3330
=> fix "fix-bundles" in PostUpdateScript.php

translations/messages.en.xlf
I went through the translations and fixed any typos I found. I noticed some of the phrases didn't sound that natural or native, so I adjusted those, I understand if you don't like the new wording :-)
=> Fixed some typos and made some phrases more natural/native sounding

assets/js/app/editor/Components/Image.vue
Change for the filebrowser. Altered the thumbnail images, so they are a bit smaller.
=> Thumbnail change/resize for the Bolt image filebrowser

assets/js/app/ajax-save.js
Ajaxy was enabled in "new" content creation.
Fixes #3376
=> Don't save content twice, if Ajaxy saving is enabled

src/Utils/Excerpt.php
=> Fix excerpt of search result when there is no whitespace in text

config/bolt/config.yaml, src/Controller/ImageController.php
This PR is based on: https://github.com/bolt/core/pull/3402 which should be reviewed/merged before this one.
=> Default thumbnail crop config

templates/_partials/fields/hidden.html.twig
=> Only overwrite name / id for a hidden field if unspecified

translations/messages.en.xlf
One of unit id was not unique. So fixed it by change to unique.
=> Fix messages.en.xlf

translations/messages.ru.xlf
1. Finished full translation into Russian.
2. Many strings was edited and fixed;
3. As well as many strings was translated first time.
4. Updated with new strings by messages.en.xlf and also transtated.
A complete and much more holistic translation made in the same style.
=> Full translation into Russian

src/Menu/FrontendMenuBuilder.php
=> Fix FrontendMenuBuilder.php when content type does not exists

src/Controller/Frontend/TaxonomyController.php
Allow to change number of records displaying in taxonomy listing
=> Fix listing_records in taxonomy

translations/messages.ru.xlf, translations/security.ru.xlf, translations/validators.ru.xlf
1. Was added missing string(s) from English to Russian files.
2. Few strings was edited to more accurate translation.
3. Fixed few typos.
Hope you will find it valuable.
As well, you can point me some other lang files which is still waiting for translation (as I understood in Bolt 5 core is no more lang files).
Thank you!
=> Updated Russian language

src/Controller/Backend/Async/UploadController.php
Fixes two oversights:
- Validate that the submitted URL is an actual http(s) URL by utilising the available Symfony constraint
- Download the temporary file to a dedicated folder using a randomised name in the configured Symfony cache folder instead of the public assets folder
=> Validate submitted URL validity before accessing URL

.github/ISSUE_TEMPLATE/1_Bug.md
Change the Bolt version list and PHP version list.
=> update Issue template

composer.json
=> :arrow_up: Update dependency php-translation/symfony-bundle

composer.json
=> :arrow_up: update siriusphp/upload

composer.json
=> :arrow_up: Update dependency symfony/webpack-encore-bundle

composer.json
See #3551 
Image resizing tested :heavy_check_mark:
=> :arrow_up: Update dependency league/glide-symfony

translations/messages.fr.xlf
This PR solve the issue #3462 and sync the french translation with english file.
=> :fr: Sync French translation from english file
